In [ ]:
import json
import pandas as pd
import numpy as np
from collections import Counter

In [ ]:
with open("candidates.jsonl", "r", encoding="utf-8") as f:
    print(f.readline())

{"candidate_id": "CAND_0000001", "profile": {"anonymized_name": "Ira Vora", "headline": "Backend Engineer | SQL, Spark, Cloud", "summary": "Software / data professional with 6.9 years of experience building data pipelines, backend systems, and analytics infrastructure. I'm a backend/data hybrid \u2014 Spark, Airflow, SQL warehouses are home territory; I'm building competence on the ML side. My toolkit is solid on the data engineering side \u2014 Python, SQL, Spark, Airflow, warehouse design \u2014 and I've completed a couple of self-directed ML projects (Kaggle competitions, side projects fine-tuning small models). Interested in transitioning toward more AI/ML-focused work, ideally at a company where I can leverage my existing data-infra skills while learning modern ML practice.", "location": "Toronto", "country": "Canada", "years_of_experience": 6.9, "current_title": "Backend Engineer", "current_company": "Mindtree", "current_company_size": "10001+", "current_industry": "IT Services"}, "career_history": [{"company": "Mindtree", "title": "Backend Engineer", "start_date": "2024-03-08", "end_date": null, "duration_months": 27, "is_current": true, "industry": "IT Services", "company_size": "10001+", "description": "Implemented streaming data pipelines on Kafka and Spark Streaming for a real-time user-activity processing platform. Designed the schema-registry integration, the watermark/state management approach, and the deduplication logic for late-arriving events. Worked closely with the data science team to make sure feature pipelines aligned with what their models needed. Most of my career has been data engineering, with some adjacent ML exposure."}, {"company": "Dunder Mifflin", "title": "Analytics Engineer", "start_date": "2019-07-03", "end_date": "2024-01-08", "duration_months": 55, "is_current": false, "industry": "Paper Products", "company_size": "201-500", "description": "Built and maintained data pipelines on Apache Airflow processing ~500GB of daily transactional data across 12 source systems. Worked extensively with Spark (PySpark) for batch processing and dbt for the transformation/modeling layer in our Snowflake warehouse. Owned the on-call rotation for data quality issues \u2014 wrote most of the data quality checks that detect schema drift and unusual volume changes. The pipeline supports the analytics team and a few internal ML models."}], "education": [{"institution": "Lovely Professional University", "degree": "B.E.", "field_of_study": "Computer Science", "start_year": 2017, "end_year": 2020, "grade": "8.24 CGPA", "tier": "tier_3"}], "skills": [{"name": "Tailwind", "proficiency": "intermediate", "endorsements": 3, "duration_months": 13}, {"name": "NLP", "proficiency": "advanced", "endorsements": 37, "duration_months": 26}, {"name": "Image Classification", "proficiency": "advanced", "endorsements": 7, "duration_months": 40}, {"name": "Fine-tuning LLMs", "proficiency": "advanced", "endorsements": 21, "duration_months": 36}, {"name": "Weights & Biases", "proficiency": "intermediate", "endorsements": 13, "duration_months": 30}, {"name": "Speech Recognition", "proficiency": "advanced", "endorsements": 52, "duration_months": 33}, {"name": "Photoshop", "proficiency": "intermediate", "endorsements": 8, "duration_months": 24}, {"name": "TTS", "proficiency": "advanced", "endorsements": 56, "duration_months": 60}, {"name": "LoRA", "proficiency": "intermediate", "endorsements": 0, "duration_months": 28}, {"name": "Apache Beam", "proficiency": "intermediate", "endorsements": 4, "duration_months": 9}, {"name": "AWS", "proficiency": "beginner", "endorsements": 5, "duration_months": 8}, {"name": "Flask", "proficiency": "beginner", "endorsements": 15, "duration_months": 15}, {"name": "BentoML", "proficiency": "intermediate", "endorsements": 3, "duration_months": 36}, {"name": "Milvus", "proficiency": "advanced", "endorsements": 40, "duration_months": 35}, {"name": "GANs", "proficiency": "advanced", "endorsements": 12, "duration_months": 19}, {"name": "Statistical Modeling", "proficiency": "intermediate", "endorsements": 9, "duration_months": 8}, {"name": "GCP", "proficiency": "beginner", "endorsements": 7, "duration_months": 2}], "certifications": [], "languages": [{"language": "English", "proficiency": "professional"}, {"language": "Hindi", "proficiency": "conversational"}], "redrob_signals": {"profile_completeness_score": 86.9, "signup_date": "2025-10-16", "last_active_date": "2026-05-20", "open_to_work_flag": true, "profile_views_received_30d": 23, "applications_submitted_30d": 2, "recruiter_response_rate": 0.34, "avg_response_time_hours": 177.8, "skill_assessment_scores": {"NLP": 38.8, "Image Classification": 64.8, "Fine-tuning LLMs": 41.6, "Speech Recognition": 53.7}, "connection_count": 356, "endorsements_received": 35, "notice_period_days": 60, "expected_salary_range_inr_lpa": {"min": 18.7, "max": 36.1}, "preferred_work_mode": "onsite", "willing_to_relocate": false, "github_activity_score": 9.2, "search_appearance_30d": 249, "saved_by_recruiters_30d": 4, "interview_completion_rate": 0.71, "offer_acceptance_rate": 0.58, "verified_email": true, "verified_phone": true, "linkedin_connected": false}}

In [ ]:
!rm candidates.jsonl

In [ ]:
from zipfile import ZipFile

with ZipFile("/content/[PUB] India_runs_data_and_ai_challenge (1).zip", "r") as z:
    z.extract(
        "[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/candidates.jsonl",
        "."
    )

In [ ]:
import os

print(os.path.getsize(
    "[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/candidates.jsonl"
) / (1024*1024))

464.6872549057007

In [ ]:
import json

records = []

with open(
    "[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/candidates.jsonl",
    "r",
    encoding="utf-8"
) as f:
    for line in f:
        records.append(json.loads(line))

print(len(records))

100000

In [ ]:
import pprint

pprint.pprint(records[0], width=120)

{'candidate_id': 'CAND_0000001',
 'career_history': [{'company': 'Mindtree',
                     'company_size': '10001+',
                     'description': 'Implemented streaming data pipelines on Kafka and Spark Streaming for a real-time '
                                    'user-activity processing platform. Designed the schema-registry integration, the '
                                    'watermark/state management approach, and the deduplication logic for '
                                    'late-arriving events. Worked closely with the data science team to make sure '
                                    'feature pipelines aligned with what their models needed. Most of my career has '
                                    'been data engineering, with some adjacent ML exposure.',
                     'duration_months': 27,
                     'end_date': None,
                     'industry': 'IT Services',
                     'is_current': True,
                     'start_date': '2024-03-08',
                     'title': 'Backend Engineer'},
                    {'company': 'Dunder Mifflin',
                     'company_size': '201-500',
                     'description': 'Built and maintained data pipelines on Apache Airflow processing ~500GB of daily '
                                    'transactional data across 12 source systems. Worked extensively with Spark '
                                    '(PySpark) for batch processing and dbt for the transformation/modeling layer in '
                                    'our Snowflake warehouse. Owned the on-call rotation for data quality issues — '
                                    'wrote most of the data quality checks that detect schema drift and unusual volume '
                                    'changes. The pipeline supports the analytics team and a few internal ML models.',
                     'duration_months': 55,
                     'end_date': '2024-01-08',
                     'industry': 'Paper Products',
                     'is_current': False,
                     'start_date': '2019-07-03',
                     'title': 'Analytics Engineer'}],
 'certifications': [],
 'education': [{'degree': 'B.E.',
                'end_year': 2020,
                'field_of_study': 'Computer Science',
                'grade': '8.24 CGPA',
                'institution': 'Lovely Professional University',
                'start_year': 2017,
                'tier': 'tier_3'}],
 'languages': [{'language': 'English', 'proficiency': 'professional'},
               {'language': 'Hindi', 'proficiency': 'conversational'}],
 'profile': {'anonymized_name': 'Ira Vora',
             'country': 'Canada',
             'current_company': 'Mindtree',
             'current_company_size': '10001+',
             'current_industry': 'IT Services',
             'current_title': 'Backend Engineer',
             'headline': 'Backend Engineer | SQL, Spark, Cloud',
             'location': 'Toronto',
             'summary': 'Software / data professional with 6.9 years of experience building data pipelines, backend '
                        "systems, and analytics infrastructure. I'm a backend/data hybrid — Spark, Airflow, SQL "
                        "warehouses are home territory; I'm building competence on the ML side. My toolkit is solid on "
                        "the data engineering side — Python, SQL, Spark, Airflow, warehouse design — and I've "
                        'completed a couple of self-directed ML projects (Kaggle competitions, side projects '
                        'fine-tuning small models). Interested in transitioning toward more AI/ML-focused work, '
                        'ideally at a company where I can leverage my existing data-infra skills while learning modern '
                        'ML practice.',
             'years_of_experience': 6.9},
 'redrob_signals': {'applications_submitted_30d': 2,
                    'avg_response_time_hours': 177.8,
                    'connection_count': 356,
                    'endorsements_received': 35,
                    'expected_salary_range_inr_lpa': {'max': 36.1, 'min': 18.7},
                    'github_activity_score': 9.2,
                    'interview_completion_rate': 0.71,
                    'last_active_date': '2026-05-20',
                    'linkedin_connected': False,
                    'notice_period_days': 60,
                    'offer_acceptance_rate': 0.58,
                    'open_to_work_flag': True,
                    'preferred_work_mode': 'onsite',
                    'profile_completeness_score': 86.9,
                    'profile_views_received_30d': 23,
                    'recruiter_response_rate': 0.34,
                    'saved_by_recruiters_30d': 4,
                    'search_appearance_30d': 249,
                    'signup_date': '2025-10-16',
                    'skill_assessment_scores': {'Fine-tuning LLMs': 41.6,
                                                'Image Classification': 64.8,
                                                'NLP': 38.8,
                                                'Speech Recognition': 53.7},
                    'verified_email': True,
                    'verified_phone': True,
                    'willing_to_relocate': False},
 'skills': [{'duration_months': 13, 'endorsements': 3, 'name': 'Tailwind', 'proficiency': 'intermediate'},
            {'duration_months': 26, 'endorsements': 37, 'name': 'NLP', 'proficiency': 'advanced'},
            {'duration_months': 40, 'endorsements': 7, 'name': 'Image Classification', 'proficiency': 'advanced'},
            {'duration_months': 36, 'endorsements': 21, 'name': 'Fine-tuning LLMs', 'proficiency': 'advanced'},
            {'duration_months': 30, 'endorsements': 13, 'name': 'Weights & Biases', 'proficiency': 'intermediate'},
            {'duration_months': 33, 'endorsements': 52, 'name': 'Speech Recognition', 'proficiency': 'advanced'},
            {'duration_months': 24, 'endorsements': 8, 'name': 'Photoshop', 'proficiency': 'intermediate'},
            {'duration_months': 60, 'endorsements': 56, 'name': 'TTS', 'proficiency': 'advanced'},
            {'duration_months': 28, 'endorsements': 0, 'name': 'LoRA', 'proficiency': 'intermediate'},
            {'duration_months': 9, 'endorsements': 4, 'name': 'Apache Beam', 'proficiency': 'intermediate'},
            {'duration_months': 8, 'endorsements': 5, 'name': 'AWS', 'proficiency': 'beginner'},
            {'duration_months': 15, 'endorsements': 15, 'name': 'Flask', 'proficiency': 'beginner'},
            {'duration_months': 36, 'endorsements': 3, 'name': 'BentoML', 'proficiency': 'intermediate'},
            {'duration_months': 35, 'endorsements': 40, 'name': 'Milvus', 'proficiency': 'advanced'},
            {'duration_months': 19, 'endorsements': 12, 'name': 'GANs', 'proficiency': 'advanced'},
            {'duration_months': 8, 'endorsements': 9, 'name': 'Statistical Modeling', 'proficiency': 'intermediate'},
            {'duration_months': 2, 'endorsements': 7, 'name': 'GCP', 'proficiency': 'beginner'}]}

In [ ]:
pprint.pprint(records[0], width=120)

{'candidate_id': 'CAND_0000001',
 'career_history': [{'company': 'Mindtree',
                     'company_size': '10001+',
                     'description': 'Implemented streaming data pipelines on Kafka and Spark Streaming for a real-time '
                                    'user-activity processing platform. Designed the schema-registry integration, the '
                                    'watermark/state management approach, and the deduplication logic for '
                                    'late-arriving events. Worked closely with the data science team to make sure '
                                    'feature pipelines aligned with what their models needed. Most of my career has '
                                    'been data engineering, with some adjacent ML exposure.',
                     'duration_months': 27,
                     'end_date': None,
                     'industry': 'IT Services',
                     'is_current': True,
                     'start_date': '2024-03-08',
                     'title': 'Backend Engineer'},
                    {'company': 'Dunder Mifflin',
                     'company_size': '201-500',
                     'description': 'Built and maintained data pipelines on Apache Airflow processing ~500GB of daily '
                                    'transactional data across 12 source systems. Worked extensively with Spark '
                                    '(PySpark) for batch processing and dbt for the transformation/modeling layer in '
                                    'our Snowflake warehouse. Owned the on-call rotation for data quality issues — '
                                    'wrote most of the data quality checks that detect schema drift and unusual volume '
                                    'changes. The pipeline supports the analytics team and a few internal ML models.',
                     'duration_months': 55,
                     'end_date': '2024-01-08',
                     'industry': 'Paper Products',
                     'is_current': False,
                     'start_date': '2019-07-03',
                     'title': 'Analytics Engineer'}],
 'certifications': [],
 'education': [{'degree': 'B.E.',
                'end_year': 2020,
                'field_of_study': 'Computer Science',
                'grade': '8.24 CGPA',
                'institution': 'Lovely Professional University',
                'start_year': 2017,
                'tier': 'tier_3'}],
 'languages': [{'language': 'English', 'proficiency': 'professional'},
               {'language': 'Hindi', 'proficiency': 'conversational'}],
 'profile': {'anonymized_name': 'Ira Vora',
             'country': 'Canada',
             'current_company': 'Mindtree',
             'current_company_size': '10001+',
             'current_industry': 'IT Services',
             'current_title': 'Backend Engineer',
             'headline': 'Backend Engineer | SQL, Spark, Cloud',
             'location': 'Toronto',
             'summary': 'Software / data professional with 6.9 years of experience building data pipelines, backend '
                        "systems, and analytics infrastructure. I'm a backend/data hybrid — Spark, Airflow, SQL "
                        "warehouses are home territory; I'm building competence on the ML side. My toolkit is solid on "
                        "the data engineering side — Python, SQL, Spark, Airflow, warehouse design — and I've "
                        'completed a couple of self-directed ML projects (Kaggle competitions, side projects '
                        'fine-tuning small models). Interested in transitioning toward more AI/ML-focused work, '
                        'ideally at a company where I can leverage my existing data-infra skills while learning modern '
                        'ML practice.',
             'years_of_experience': 6.9},
 'redrob_signals': {'applications_submitted_30d': 2,
                    'avg_response_time_hours': 177.8,
                    'connection_count': 356,
                    'endorsements_received': 35,
                    'expected_salary_range_inr_lpa': {'max': 36.1, 'min': 18.7},
                    'github_activity_score': 9.2,
                    'interview_completion_rate': 0.71,
                    'last_active_date': '2026-05-20',
                    'linkedin_connected': False,
                    'notice_period_days': 60,
                    'offer_acceptance_rate': 0.58,
                    'open_to_work_flag': True,
                    'preferred_work_mode': 'onsite',
                    'profile_completeness_score': 86.9,
                    'profile_views_received_30d': 23,
                    'recruiter_response_rate': 0.34,
                    'saved_by_recruiters_30d': 4,
                    'search_appearance_30d': 249,
                    'signup_date': '2025-10-16',
                    'skill_assessment_scores': {'Fine-tuning LLMs': 41.6,
                                                'Image Classification': 64.8,
                                                'NLP': 38.8,
                                                'Speech Recognition': 53.7},
                    'verified_email': True,
                    'verified_phone': True,
                    'willing_to_relocate': False},
 'skills': [{'duration_months': 13, 'endorsements': 3, 'name': 'Tailwind', 'proficiency': 'intermediate'},
            {'duration_months': 26, 'endorsements': 37, 'name': 'NLP', 'proficiency': 'advanced'},
            {'duration_months': 40, 'endorsements': 7, 'name': 'Image Classification', 'proficiency': 'advanced'},
            {'duration_months': 36, 'endorsements': 21, 'name': 'Fine-tuning LLMs', 'proficiency': 'advanced'},
            {'duration_months': 30, 'endorsements': 13, 'name': 'Weights & Biases', 'proficiency': 'intermediate'},
            {'duration_months': 33, 'endorsements': 52, 'name': 'Speech Recognition', 'proficiency': 'advanced'},
            {'duration_months': 24, 'endorsements': 8, 'name': 'Photoshop', 'proficiency': 'intermediate'},
            {'duration_months': 60, 'endorsements': 56, 'name': 'TTS', 'proficiency': 'advanced'},
            {'duration_months': 28, 'endorsements': 0, 'name': 'LoRA', 'proficiency': 'intermediate'},
            {'duration_months': 9, 'endorsements': 4, 'name': 'Apache Beam', 'proficiency': 'intermediate'},
            {'duration_months': 8, 'endorsements': 5, 'name': 'AWS', 'proficiency': 'beginner'},
            {'duration_months': 15, 'endorsements': 15, 'name': 'Flask', 'proficiency': 'beginner'},
            {'duration_months': 36, 'endorsements': 3, 'name': 'BentoML', 'proficiency': 'intermediate'},
            {'duration_months': 35, 'endorsements': 40, 'name': 'Milvus', 'proficiency': 'advanced'},
            {'duration_months': 19, 'endorsements': 12, 'name': 'GANs', 'proficiency': 'advanced'},
            {'duration_months': 8, 'endorsements': 9, 'name': 'Statistical Modeling', 'proficiency': 'intermediate'},
            {'duration_months': 2, 'endorsements': 7, 'name': 'GCP', 'proficiency': 'beginner'}]}

In [ ]:
records[0]["career_history"][0]

{'company': 'Mindtree',
 'title': 'Backend Engineer',
 'start_date': '2024-03-08',
 'end_date': None,
 'duration_months': 27,
 'is_current': True,
 'industry': 'IT Services',
 'company_size': '10001+',
 'description': 'Implemented streaming data pipelines on Kafka and Spark Streaming for a real-time user-activity processing platform. Designed the schema-registry integration, the watermark/state management approach, and the deduplication logic for late-arriving events. Worked closely with the data science team to make sure feature pipelines aligned with what their models needed. Most of my career has been data engineering, with some adjacent ML exposure.'}

In [ ]:
records[0]["skills"][0]

{'name': 'Tailwind',
 'proficiency': 'intermediate',
 'endorsements': 3,
 'duration_months': 13}

In [ ]:
records[0]["skills"][0]

{'name': 'Tailwind',
 'proficiency': 'intermediate',
 'endorsements': 3,
 'duration_months': 13}

In [ ]:
titles = []

for r in records:
    titles.append(r["profile"]["current_title"])

title_counts = pd.Series(titles).value_counts()

title_counts.head(50)

Business Analyst                    5833
HR Manager                          5830
Mechanical Engineer                 5791
Accountant                          5764
Project Manager                     5754
Customer Support                    5750
Operations Manager                  5744
Content Writer                      5727
Sales Executive                     5713
Civil Engineer                      5702
Graphic Designer                    5689
Marketing Manager                   5524
Software Engineer                   3450
Full Stack Developer                2873
Cloud Engineer                      2836
Java Developer                      2809
.NET Developer                      2788
DevOps Engineer                     2787
Mobile Developer                    2757
Frontend Engineer                   2738
QA Engineer                         2682
Analytics Engineer                   764
Data Engineer                        744
Data Analyst                         728
Backend Engineer                     704
Senior Data Engineer                 687
Senior Software Engineer             653
ML Engineer                          167
AI Research Engineer                 153
Data Scientist                       145
Senior Software Engineer (ML)        142
Computer Vision Engineer             132
Junior ML Engineer                   131
AI Specialist                        130
Recommendation Systems Engineer       26
Machine Learning Engineer             24
Applied ML Engineer                   23
Search Engineer                       23
AI Engineer                           21
Senior Data Scientist                 19
NLP Engineer                          14
Senior Machine Learning Engineer       6
Senior NLP Engineer                    6
Staff Machine Learning Engineer        6
Senior AI Engineer                     4
Senior Applied Scientist               4
Lead AI Engineer                       3
Name: count, dtype: int64

In [ ]:
title_df = pd.DataFrame(title_counts)

title_df.columns = ["Count"]

title_df.head(50)

                                  Count
Business Analyst                   5833
HR Manager                         5830
Mechanical Engineer                5791
Accountant                         5764
Project Manager                    5754
Customer Support                   5750
Operations Manager                 5744
Content Writer                     5727
Sales Executive                    5713
Civil Engineer                     5702
Graphic Designer                   5689
Marketing Manager                  5524
Software Engineer                  3450
Full Stack Developer               2873
Cloud Engineer                     2836
Java Developer                     2809
.NET Developer                     2788
DevOps Engineer                    2787
Mobile Developer                   2757
Frontend Engineer                  2738
QA Engineer                        2682
Analytics Engineer                  764
Data Engineer                       744
Data Analyst                        728
Backend Engineer                    704
Senior Data Engineer                687
Senior Software Engineer            653
ML Engineer                         167
AI Research Engineer                153
Data Scientist                      145
Senior Software Engineer (ML)       142
Computer Vision Engineer            132
Junior ML Engineer                  131
AI Specialist                       130
Recommendation Systems Engineer      26
Machine Learning Engineer            24
Applied ML Engineer                  23
Search Engineer                      23
AI Engineer                          21
Senior Data Scientist                19
NLP Engineer                         14
Senior Machine Learning Engineer      6
Senior NLP Engineer                   6
Staff Machine Learning Engineer       6
Senior AI Engineer                    4
Senior Applied Scientist              4
Lead AI Engineer                      3

In [ ]:
print("Unique Titles :", len(title_counts))

Unique Titles : 47

In [ ]:
title_counts[
    title_counts.index.str.contains(
        "AI|ML|Machine|Data|Search|Recommendation|NLP|Applied|Vision",
        case=False,
        regex=True
    )
]

Data Engineer                       744
Data Analyst                        728
Senior Data Engineer                687
ML Engineer                         167
AI Research Engineer                153
Data Scientist                      145
Senior Software Engineer (ML)       142
Computer Vision Engineer            132
Junior ML Engineer                  131
AI Specialist                       130
Recommendation Systems Engineer      26
Machine Learning Engineer            24
Applied ML Engineer                  23
Search Engineer                      23
AI Engineer                          21
Senior Data Scientist                19
NLP Engineer                         14
Senior Machine Learning Engineer      6
Senior NLP Engineer                   6
Staff Machine Learning Engineer       6
Senior AI Engineer                    4
Senior Applied Scientist              4
Lead AI Engineer                      3
Name: count, dtype: int64

In [ ]:
total_jobs = 0

for r in records:
    total_jobs += len(r["career_history"])

print("Total Jobs :", total_jobs)

Total Jobs : 300171

In [ ]:
total_jobs = 0

for r in records:
    total_jobs += len(r["career_history"])

print("Total Jobs :", total_jobs)

Total Jobs : 300171

In [ ]:
career_descriptions = []

for r in records:

    for job in r["career_history"]:

        career_descriptions.append(job["description"])

In [ ]:
print("Total Descriptions :", len(career_descriptions))

Total Descriptions : 300171

In [ ]:
templates = pd.Series(career_descriptions).drop_duplicates().tolist()

print("Unique Templates :", len(templates))

Unique Templates : 44

In [ ]:
for i, desc in enumerate(templates):

    print("="*100)

    print("Template :", i)

    print(desc[:350])

====================================================================================================
Template : 0
Implemented streaming data pipelines on Kafka and Spark Streaming for a real-time user-activity processing platform. Designed the schema-registry integration, the watermark/state management approach, and the deduplication logic for late-arriving events. Worked closely with the data science team to make sure feature pipelines aligned with what their
====================================================================================================
Template : 1
Built and maintained data pipelines on Apache Airflow processing ~500GB of daily transactional data across 12 source systems. Worked extensively with Spark (PySpark) for batch processing and dbt for the transformation/modeling layer in our Snowflake warehouse. Owned the on-call rotation for data quality issues — wrote most of the data quality check
====================================================================================================
Template : 2
Customer support team lead at a SaaS product. Managed a team of 8 support agents handling tier-1 and tier-2 tickets; owned the escalation process to engineering and the customer-feedback loop to product. Built out the support knowledge base and the agent training program. Strong on the people-management side and the process side; lighter on technic
====================================================================================================
Template : 3
Mechanical engineering design role at a hardware-product company. Led the design of two product subsystems through full lifecycle: concept, DFM/DFMA review, prototype, production tooling. Comfortable with CAD (SolidWorks, Creo), FEA (ANSYS), and the typical hardware-development cadence. Worked closely with manufacturing partners on production scale
====================================================================================================
Template : 4
Content writing and SEO strategy for a tech-focused publication. Wrote longform articles on developer tools, cloud platforms, and AI/ML topics — including some that ranked on the first page of search for high-competition keywords. Managed a freelance writer pool and the editorial calendar. Recent work has been on AI-assisted content production, usi
====================================================================================================
Template : 5
Brand design and creative direction at a consumer-products company. Owned brand identity (logo, visual system, typography), packaging design, and digital creative across web and social. Led the recent rebrand and managed a small external agency for production work. Comfortable across the Adobe suite, Figma, and the production side of brand and pack
====================================================================================================
Template : 6
Business analyst at a consulting firm, working primarily with retail and CPG clients. Conducted business diagnostics, process re-engineering work, and digital transformation strategy projects. Strong on stakeholder management, structured problem-solving, and the typical consulting toolkit (slide-craft, Excel modeling, executive communication). Rece
====================================================================================================
Template : 7
Operations management role at a logistics company. Owned daily fulfillment operations across 3 warehouses, managing a team of 80 across receiving, picking, packing, and outbound. Built and tracked the operational KPIs (on-time fulfillment, accuracy, cost per order) and led the continuous improvement initiatives that drove a 22% productivity gain ov
====================================================================================================
Template : 8
Senior accounting role at a mid-sized company — month-end close, financial reporting, statutory compliance (GAAP / Ind-AS), and tax filings. Owned the GL, fixed-asset register, and the audit-readiness function. Managed a team of 3 staff accountants. Built strong process discipline around the close cycle, reducing close time from 12 days to 7 over t
====================================================================================================
Template : 9
Marketing leadership role at a B2B SaaS company. Owned the demand-generation function — content marketing, paid acquisition, SEO, email nurture. Built and managed a team of 5 across content, performance marketing, and marketing operations. Worked closely with sales on lead-quality definitions and the SDR-handoff process. Recent focus has been on ac
====================================================================================================
Template : 10
Enterprise sales of cloud software solutions into the mid-market segment. Carried a $1.8M ARR quota and consistently delivered against it across the last three years. Owned the full sales cycle: prospecting, discovery, technical evaluation (with SE support), commercial negotiation, and close. Strong on consultative selling for technical buyers; com
====================================================================================================
Template : 11
Mixed data science and analytics-engineering role at a marketing-analytics startup. Spent maybe 30% of my time on lightweight ML (clustering, classification, churn prediction in sklearn/XGBoost) and 70% on data infrastructure and dashboards. Comfortable with the modeling work but I wouldn't call myself an ML specialist. Built our experimentation fr
====================================================================================================
Template : 12
Android mobile development using Java and (more recently) Kotlin at a consumer-app company. Built and maintained multiple production features including the main shopping flow, push notification system, and the offline-first sync layer. Comfortable with the Android framework, Jetpack components, and the typical patterns (MVVM, Hilt, Coroutines). My
====================================================================================================
Template : 13
Test automation and QA engineering for a fintech product. Built and maintained the end-to-end test suite using Selenium and pytest, plus the load-testing setup using Locust. Worked closely with developers on testability patterns and with product on acceptance criteria. Recent work has been on shifting test responsibility into the dev team — moving
====================================================================================================
Template : 14
Frontend engineering at a media company. React, TypeScript, and the typical surrounding tooling (Webpack, Jest, Cypress). Built the company's design system from scratch and led the migration from a legacy AngularJS app. Strong on the frontend craft — accessibility, performance, animations — but limited backend exposure.
====================================================================================================
Template : 15
Cloud infrastructure and DevOps work at an enterprise SaaS company. Owned the AWS account architecture (VPC, IAM, networking), the Terraform modules for our service deployments, and the Kubernetes cluster operations. Designed the CI/CD pipelines (GitLab CI + ArgoCD) and the monitoring stack (Prometheus, Grafana, Loki). Strong on the infra and ops s
====================================================================================================
Template : 16
Java backend development at a large enterprise — Spring Boot microservices, Kafka for inter-service messaging, Postgres + Redis for storage. Worked on the customer onboarding flow which involved orchestrating multiple downstream services. Solid on the Spring ecosystem, transaction handling, and the operational side of Java services. Looking to eith
====================================================================================================
Template : 17
Full-stack web application development at a SaaS company. Built React-based admin interfaces and the Node.js REST API backing them. Worked across the stack: frontend components, REST endpoint design, PostgreSQL schema, deployment via Docker/Kubernetes. Comfortable in most parts of a typical web stack though my comfort zone is the backend and databa
====================================================================================================
Template : 18
Trained and shipped multiple ranking models for our product's discovery feed using XGBoost and LightGBM. Designed features across three families: content metadata, user behavior signals, and item engagement history. Owned the offline-online correlation analysis that determined which offline metrics actually predicted A/B test outcomes. Worked close
====================================================================================================
Template : 19
Owned the ranking layer for an e-commerce search product, evolving it from a hand-tuned scoring function to a learning-to-rank model over 9 months. Designed the relevance labeling pipeline (mix of click-through data and explicit human judgments), the feature pipeline, and the training/eval workflow. Most of the work was infrastructure and data qual
====================================================================================================
Template : 20
Built NLP pipelines for sentiment analysis and document classification — primarily for an internal feedback-analytics dashboard. Started with sklearn-based bag-of-words models, then moved to transformer-based classifiers (DistilBERT) for the harder classes. Comfortable with PyTorch and Hugging Face but most of my training experience has been on sma
====================================================================================================
Template : 21
Backend + data hybrid role at a growth-stage startup. Built the company's first proper data warehouse (migrating from a tangled set of Postgres replicas to a clean Snowflake setup with dbt), the orchestration layer (Airflow), and the BI integration (Looker). Shipped a couple of small predictive features but the bulk of the role was data infrastruct
====================================================================================================
Template : 22
Designed and maintained the analytical data warehouse on Snowflake supporting the BI team's ~50 dashboards. Wrote complex SQL — heavy on window functions, CTEs, and incremental modeling patterns via dbt. Worked on the data modeling side (dimensional modeling, slowly changing dimensions) as well as performance optimization (query tuning, cluster siz
====================================================================================================
Template : 23
Built computer vision models for our product's image moderation feature using PyTorch — fine-tuned ResNet variants on a labeled dataset of ~200K images. Set up the training pipeline (data loading, augmentation, evaluation) and the inference service. Most of my project work has been in CV; I'm now interested in transitioning toward NLP/LLM work but
====================================================================================================
Template : 24
Contributed to ML feature engineering and model deployment for a fraud-detection product. My main role was engineering: building the Flask-based prediction API, integrating with the feature store, and writing the model-serving observability layer. I worked closely with senior data scientists but my own modeling work was secondary — I was the produc
====================================================================================================
Template : 25
Backend development with Python (FastAPI), PostgreSQL, and Redis at a B2B SaaS product. Owned the analytics-and-reporting service which serves dashboards to ~3K paying customers. Recent work includes integrating a model-serving service (built by another team) into our API layer; my work was the integration and observability, not the model itself. S
====================================================================================================
Template : 26
Worked on customer-facing predictive modeling for an e-commerce platform — churn prediction, conversion likelihood, lifetime value estimation. Used scikit-learn and XGBoost; main models were gradient-boosted trees with ~80 hand-engineered features. The work was split roughly 60/40 between modeling and data prep / SQL. The churn model is now used by
====================================================================================================
Template : 27
Built recommendation-style features at a mid-stage startup — lighter weight than ranking systems at FAANG, but production. Used a combination of collaborative filtering (matrix factorization in implicit-feedback library) and gradient-boosted re-ranking over engagement signals. Pure ML side of the work; production deployment was handled by the platf
====================================================================================================
Template : 28
Worked on time-series forecasting models for supply-chain demand prediction at a logistics company. Built models in Prophet, LightGBM, and (for one project) a small LSTM — the LightGBM model ended up shipping. Also ran some reinforcement learning experiments for dynamic pricing but those didn't make it to production. The work was a mix of modeling,
====================================================================================================
Template : 29
Developed a semantic search feature for an internal knowledge base of ~500K documents. Used sentence-transformers (all-MiniLM-L6-v2 initially, later upgraded to bge-base) with FAISS for fast nearest-neighbor retrieval. Designed the query expansion module that handles vocabulary mismatch between user queries and document terms. Reported search-relev
====================================================================================================
Template : 30
Built a content recommendation system serving 10M+ users that combined collaborative filtering with content-based ranking. The system uses item-item similarity (via sentence-transformer embeddings) for cold starts and a gradient-boosted model trained on engagement signals for warm users. Most of my time went into the feature pipeline (~200 features
====================================================================================================
Template : 31
Built and shipped a production recommendation system at a marketplace product, going from offline experimentation to live A/B test in 5 months. The system combined collaborative filtering (matrix factorization), content-based features (TF-IDF + sentence-transformer embeddings), and a behavioral re-ranking layer. The most interesting technical chall
====================================================================================================
Template : 32
Fine-tuned LLaMA-2-7B and Mistral-7B variants using LoRA and QLoRA for domain-specific candidate-JD matching. Built the data curation pipeline that generated 200K high-quality preference pairs from recruiter labels, plus the eval harness using both ranking metrics and human-quality scores. Deployed the model via BentoML on Kubernetes with sub-200ms
====================================================================================================
Template : 33
Built a RAG-based ranking pipeline serving 50M+ queries per month for an internal recruiter-facing search product. The architecture combined BM25 + dense retrieval (BGE embeddings, FAISS HNSW) with an LLM-based re-ranker on the top-50, falling back to a learning-to-rank model when latency budget was tight. Designed the offline evaluation framework
====================================================================================================
Template : 34
Led the engineering team building infrastructure to surface relevant content to users at scale. The system processed billions of documents and served millions of queries with low latency. Most of the technical effort went into the boring-but-essential parts: index refresh, query understanding, ranking calibration, and the dashboards that made the s
====================================================================================================
Template : 35
Built systems that understand what users are looking for and connect them to the most relevant matches across a large dataset. Worked at the intersection of infrastructure, algorithms, and product judgment — none of the three were optional. Recent project was a complete overhaul of the matching layer; took it from a hand-tuned heuristic system to o
====================================================================================================
Template : 36
Implemented a RAG-based customer support chatbot integrated with our existing ticketing system. Built the document ingestion pipeline (chunking, embedding via OpenAI embeddings, storing in Pinecone) and the answer-generation layer (initially GPT-4, then a fine-tuned smaller model for cost control). Designed the evaluation framework with both automa
====================================================================================================
Template : 37
Built and operated production ML pipelines using MLflow for experiment tracking, Kubeflow for orchestration, and our internal feature store. My main project was a churn prediction model that's now used by the customer success team to prioritize outreach. Designed the model monitoring stack: data drift detection, prediction distribution checks, and
====================================================================================================
Template : 38
Owned the search and discovery experience end-to-end at a consumer product, from how content is represented internally through to how the most relevant results appear for each user's intent. The work spanned data infrastructure, ranking algorithms, evaluation methodology, and direct collaboration with product/PM on what 'relevance' actually means f
====================================================================================================
Template : 39
Shipped the personalization infrastructure: the system that learns from user behavior and improves relevance over time. Designed the offline experimentation environment, the online A/B testing framework, and the feature-engineering pipeline that connected them. Most of my time went into the boring-but-critical operational layer — feature monitoring
====================================================================================================
Template : 40
Owned the end-to-end ranking pipeline at a recommendations-heavy consumer product: candidate sourcing → embedding generation (using a fine-tuned BGE-large) → Pinecone retrieval → learning-to-rank re-scoring (XGBoost) → behavioral-signal integration. The hardest part wasn't the ML — it was the evaluation: building offline metrics that actually predi
====================================================================================================
Template : 41
Owned the design and rollout of a large-scale semantic search system serving an internal corpus of 35M+ items. Migrated the existing BM25-only retrieval to a hybrid setup combining sparse and dense vectors (sentence-transformers, MPNet-base initially, later fine-tuned BGE-large for our domain). The new system reduced p95 retrieval latency by 60% wh
====================================================================================================
Template : 42
Designed the ranking layer for the company's flagship product: how do we surface the right thing at the right time, across millions of items, for millions of users. The hard problem was rarely the modeling — it was the data pipeline that fed the models, the evaluation framework that told us whether they worked, and the operational discipline of kee

In [ ]:
templates[:5]

['Implemented streaming data pipelines on Kafka and Spark Streaming for a real-time user-activity processing platform. Designed the schema-registry integration, the watermark/state management approach, and the deduplication logic for late-arriving events. Worked closely with the data science team to make sure feature pipelines aligned with what their models needed. Most of my career has been data engineering, with some adjacent ML exposure.',
 'Built and maintained data pipelines on Apache Airflow processing ~500GB of daily transactional data across 12 source systems. Worked extensively with Spark (PySpark) for batch processing and dbt for the transformation/modeling layer in our Snowflake warehouse. Owned the on-call rotation for data quality issues — wrote most of the data quality checks that detect schema drift and unusual volume changes. The pipeline supports the analytics team and a few internal ML models.',
 'Customer support team lead at a SaaS product. Managed a team of 8 support agents handling tier-1 and tier-2 tickets; owned the escalation process to engineering and the customer-feedback loop to product. Built out the support knowledge base and the agent training program. Strong on the people-management side and the process side; lighter on technical depth beyond product expertise.',
 'Mechanical engineering design role at a hardware-product company. Led the design of two product subsystems through full lifecycle: concept, DFM/DFMA review, prototype, production tooling. Comfortable with CAD (SolidWorks, Creo), FEA (ANSYS), and the typical hardware-development cadence. Worked closely with manufacturing partners on production scale-up.',
 'Content writing and SEO strategy for a tech-focused publication. Wrote longform articles on developer tools, cloud platforms, and AI/ML topics — including some that ranked on the first page of search for high-competition keywords. Managed a freelance writer pool and the editorial calendar. Recent work has been on AI-assisted content production, using LLM tools for research, drafting, and editing while maintaining editorial quality.']

In [ ]:
for i, desc in enumerate(templates):

    print("=" * 120)
    print(f"Template {i}")

    if "recommendation" in desc.lower():
        print("Category : Recommendation Systems")

    elif "search" in desc.lower():
        print("Category : Search / Ranking")

    elif "semantic" in desc.lower():
        print("Category : Semantic Search")

    elif "rag" in desc.lower():
        print("Category : RAG")

    elif "llama" in desc.lower() or "mistral" in desc.lower():
        print("Category : LLM Fine-tuning")

    elif "computer vision" in desc.lower():
        print("Category : Computer Vision")

    elif "time-series" in desc.lower():
        print("Category : Time Series")

    elif "churn" in desc.lower():
        print("Category : Predictive ML")

    else:
        print("Category : Other")

    print(desc[:300])

========================================================================================================================
Template 0
Category : Other
Implemented streaming data pipelines on Kafka and Spark Streaming for a real-time user-activity processing platform. Designed the schema-registry integration, the watermark/state management approach, and the deduplication logic for late-arriving events. Worked closely with the data science team to m
========================================================================================================================
Template 1
Category : Other
Built and maintained data pipelines on Apache Airflow processing ~500GB of daily transactional data across 12 source systems. Worked extensively with Spark (PySpark) for batch processing and dbt for the transformation/modeling layer in our Snowflake warehouse. Owned the on-call rotation for data qua
========================================================================================================================
Template 2
Category : Other
Customer support team lead at a SaaS product. Managed a team of 8 support agents handling tier-1 and tier-2 tickets; owned the escalation process to engineering and the customer-feedback loop to product. Built out the support knowledge base and the agent training program. Strong on the people-manage
========================================================================================================================
Template 3
Category : Other
Mechanical engineering design role at a hardware-product company. Led the design of two product subsystems through full lifecycle: concept, DFM/DFMA review, prototype, production tooling. Comfortable with CAD (SolidWorks, Creo), FEA (ANSYS), and the typical hardware-development cadence. Worked close
========================================================================================================================
Template 4
Category : Search / Ranking
Content writing and SEO strategy for a tech-focused publication. Wrote longform articles on developer tools, cloud platforms, and AI/ML topics — including some that ranked on the first page of search for high-competition keywords. Managed a freelance writer pool and the editorial calendar. Recent wo
========================================================================================================================
Template 5
Category : Other
Brand design and creative direction at a consumer-products company. Owned brand identity (logo, visual system, typography), packaging design, and digital creative across web and social. Led the recent rebrand and managed a small external agency for production work. Comfortable across the Adobe suite
========================================================================================================================
Template 6
Category : Other
Business analyst at a consulting firm, working primarily with retail and CPG clients. Conducted business diagnostics, process re-engineering work, and digital transformation strategy projects. Strong on stakeholder management, structured problem-solving, and the typical consulting toolkit (slide-cra
========================================================================================================================
Template 7
Category : Other
Operations management role at a logistics company. Owned daily fulfillment operations across 3 warehouses, managing a team of 80 across receiving, picking, packing, and outbound. Built and tracked the operational KPIs (on-time fulfillment, accuracy, cost per order) and led the continuous improvement
========================================================================================================================
Template 8
Category : Other
Senior accounting role at a mid-sized company — month-end close, financial reporting, statutory compliance (GAAP / Ind-AS), and tax filings. Owned the GL, fixed-asset register, and the audit-readiness function. Managed a team of 3 staff accountants. Built strong process discipline around the close c
========================================================================================================================
Template 9
Category : Other
Marketing leadership role at a B2B SaaS company. Owned the demand-generation function — content marketing, paid acquisition, SEO, email nurture. Built and managed a team of 5 across content, performance marketing, and marketing operations. Worked closely with sales on lead-quality definitions and th
========================================================================================================================
Template 10
Category : Other
Enterprise sales of cloud software solutions into the mid-market segment. Carried a $1.8M ARR quota and consistently delivered against it across the last three years. Owned the full sales cycle: prospecting, discovery, technical evaluation (with SE support), commercial negotiation, and close. Strong
========================================================================================================================
Template 11
Category : Predictive ML
Mixed data science and analytics-engineering role at a marketing-analytics startup. Spent maybe 30% of my time on lightweight ML (clustering, classification, churn prediction in sklearn/XGBoost) and 70% on data infrastructure and dashboards. Comfortable with the modeling work but I wouldn't call mys
========================================================================================================================
Template 12
Category : Other
Android mobile development using Java and (more recently) Kotlin at a consumer-app company. Built and maintained multiple production features including the main shopping flow, push notification system, and the offline-first sync layer. Comfortable with the Android framework, Jetpack components, and
========================================================================================================================
Template 13
Category : Other
Test automation and QA engineering for a fintech product. Built and maintained the end-to-end test suite using Selenium and pytest, plus the load-testing setup using Locust. Worked closely with developers on testability patterns and with product on acceptance criteria. Recent work has been on shifti
========================================================================================================================
Template 14
Category : Other
Frontend engineering at a media company. React, TypeScript, and the typical surrounding tooling (Webpack, Jest, Cypress). Built the company's design system from scratch and led the migration from a legacy AngularJS app. Strong on the frontend craft — accessibility, performance, animations — but limi
========================================================================================================================
Template 15
Category : Other
Cloud infrastructure and DevOps work at an enterprise SaaS company. Owned the AWS account architecture (VPC, IAM, networking), the Terraform modules for our service deployments, and the Kubernetes cluster operations. Designed the CI/CD pipelines (GitLab CI + ArgoCD) and the monitoring stack (Prometh
========================================================================================================================
Template 16
Category : RAG
Java backend development at a large enterprise — Spring Boot microservices, Kafka for inter-service messaging, Postgres + Redis for storage. Worked on the customer onboarding flow which involved orchestrating multiple downstream services. Solid on the Spring ecosystem, transaction handling, and the
========================================================================================================================
Template 17
Category : Other
Full-stack web application development at a SaaS company. Built React-based admin interfaces and the Node.js REST API backing them. Worked across the stack: frontend components, REST endpoint design, PostgreSQL schema, deployment via Docker/Kubernetes. Comfortable in most parts of a typical web stac
========================================================================================================================
Template 18
Category : Other
Trained and shipped multiple ranking models for our product's discovery feed using XGBoost and LightGBM. Designed features across three families: content metadata, user behavior signals, and item engagement history. Owned the offline-online correlation analysis that determined which offline metrics
========================================================================================================================
Template 19
Category : Search / Ranking
Owned the ranking layer for an e-commerce search product, evolving it from a hand-tuned scoring function to a learning-to-rank model over 9 months. Designed the relevance labeling pipeline (mix of click-through data and explicit human judgments), the feature pipeline, and the training/eval workflow.
========================================================================================================================
Template 20
Category : Other
Built NLP pipelines for sentiment analysis and document classification — primarily for an internal feedback-analytics dashboard. Started with sklearn-based bag-of-words models, then moved to transformer-based classifiers (DistilBERT) for the harder classes. Comfortable with PyTorch and Hugging Face
========================================================================================================================
Template 21
Category : Other
Backend + data hybrid role at a growth-stage startup. Built the company's first proper data warehouse (migrating from a tangled set of Postgres replicas to a clean Snowflake setup with dbt), the orchestration layer (Airflow), and the BI integration (Looker). Shipped a couple of small predictive feat
========================================================================================================================
Template 22
Category : Other
Designed and maintained the analytical data warehouse on Snowflake supporting the BI team's ~50 dashboards. Wrote complex SQL — heavy on window functions, CTEs, and incremental modeling patterns via dbt. Worked on the data modeling side (dimensional modeling, slowly changing dimensions) as well as p
========================================================================================================================
Template 23
Category : Computer Vision
Built computer vision models for our product's image moderation feature using PyTorch — fine-tuned ResNet variants on a labeled dataset of ~200K images. Set up the training pipeline (data loading, augmentation, evaluation) and the inference service. Most of my project work has been in CV; I'm now in
========================================================================================================================
Template 24
Category : Other
Contributed to ML feature engineering and model deployment for a fraud-detection product. My main role was engineering: building the Flask-based prediction API, integrating with the feature store, and writing the model-serving observability layer. I worked closely with senior data scientists but my
========================================================================================================================
Template 25
Category : Other
Backend development with Python (FastAPI), PostgreSQL, and Redis at a B2B SaaS product. Owned the analytics-and-reporting service which serves dashboards to ~3K paying customers. Recent work includes integrating a model-serving service (built by another team) into our API layer; my work was the inte
========================================================================================================================
Template 26
Category : Predictive ML
Worked on customer-facing predictive modeling for an e-commerce platform — churn prediction, conversion likelihood, lifetime value estimation. Used scikit-learn and XGBoost; main models were gradient-boosted trees with ~80 hand-engineered features. The work was split roughly 60/40 between modeling a
========================================================================================================================
Template 27
Category : Recommendation Systems
Built recommendation-style features at a mid-stage startup — lighter weight than ranking systems at FAANG, but production. Used a combination of collaborative filtering (matrix factorization in implicit-feedback library) and gradient-boosted re-ranking over engagement signals. Pure ML side of the wo
========================================================================================================================
Template 28
Category : Time Series
Worked on time-series forecasting models for supply-chain demand prediction at a logistics company. Built models in Prophet, LightGBM, and (for one project) a small LSTM — the LightGBM model ended up shipping. Also ran some reinforcement learning experiments for dynamic pricing but those didn't make
========================================================================================================================
Template 29
Category : Search / Ranking
Developed a semantic search feature for an internal knowledge base of ~500K documents. Used sentence-transformers (all-MiniLM-L6-v2 initially, later upgraded to bge-base) with FAISS for fast nearest-neighbor retrieval. Designed the query expansion module that handles vocabulary mismatch between user
========================================================================================================================
Template 30
Category : Recommendation Systems
Built a content recommendation system serving 10M+ users that combined collaborative filtering with content-based ranking. The system uses item-item similarity (via sentence-transformer embeddings) for cold starts and a gradient-boosted model trained on engagement signals for warm users. Most of my
========================================================================================================================
Template 31
Category : Recommendation Systems
Built and shipped a production recommendation system at a marketplace product, going from offline experimentation to live A/B test in 5 months. The system combined collaborative filtering (matrix factorization), content-based features (TF-IDF + sentence-transformer embeddings), and a behavioral re-r
========================================================================================================================
Template 32
Category : LLM Fine-tuning
Fine-tuned LLaMA-2-7B and Mistral-7B variants using LoRA and QLoRA for domain-specific candidate-JD matching. Built the data curation pipeline that generated 200K high-quality preference pairs from recruiter labels, plus the eval harness using both ranking metrics and human-quality scores. Deployed
========================================================================================================================
Template 33
Category : Search / Ranking
Built a RAG-based ranking pipeline serving 50M+ queries per month for an internal recruiter-facing search product. The architecture combined BM25 + dense retrieval (BGE embeddings, FAISS HNSW) with an LLM-based re-ranker on the top-50, falling back to a learning-to-rank model when latency budget was
========================================================================================================================
Template 34
Category : Other
Led the engineering team building infrastructure to surface relevant content to users at scale. The system processed billions of documents and served millions of queries with low latency. Most of the technical effort went into the boring-but-essential parts: index refresh, query understanding, ranki
========================================================================================================================
Template 35
Category : Other
Built systems that understand what users are looking for and connect them to the most relevant matches across a large dataset. Worked at the intersection of infrastructure, algorithms, and product judgment — none of the three were optional. Recent project was a complete overhaul of the matching laye
========================================================================================================================
Template 36
Category : RAG
Implemented a RAG-based customer support chatbot integrated with our existing ticketing system. Built the document ingestion pipeline (chunking, embedding via OpenAI embeddings, storing in Pinecone) and the answer-generation layer (initially GPT-4, then a fine-tuned smaller model for cost control).
========================================================================================================================
Template 37
Category : Predictive ML
Built and operated production ML pipelines using MLflow for experiment tracking, Kubeflow for orchestration, and our internal feature store. My main project was a churn prediction model that's now used by the customer success team to prioritize outreach. Designed the model monitoring stack: data dri
========================================================================================================================
Template 38
Category : Search / Ranking
Owned the search and discovery experience end-to-end at a consumer product, from how content is represented internally through to how the most relevant results appear for each user's intent. The work spanned data infrastructure, ranking algorithms, evaluation methodology, and direct collaboration wi
========================================================================================================================
Template 39
Category : Other
Shipped the personalization infrastructure: the system that learns from user behavior and improves relevance over time. Designed the offline experimentation environment, the online A/B testing framework, and the feature-engineering pipeline that connected them. Most of my time went into the boring-b
========================================================================================================================
Template 40
Category : Recommendation Systems
Owned the end-to-end ranking pipeline at a recommendations-heavy consumer product: candidate sourcing → embedding generation (using a fine-tuned BGE-large) → Pinecone retrieval → learning-to-rank re-scoring (XGBoost) → behavioral-signal integration. The hardest part wasn't the ML — it was the evalua
========================================================================================================================
Template 41
Category : Search / Ranking
Owned the design and rollout of a large-scale semantic search system serving an internal corpus of 35M+ items. Migrated the existing BM25-only retrieval to a hybrid setup combining sparse and dense vectors (sentence-transformers, MPNet-base initially, later fine-tuned BGE-large for our domain). The
========================================================================================================================
Template 42
Category : Other
Designed the ranking layer for the company's flagship product: how do we surface the right thing at the right time, across millions of items, for millions of users. The hard problem was rarely the modeling — it was the data pipeline that fed the models, the evaluation framework that told us whether
========================================================================================================================
Template 43
Category : Search / Ranking

In [ ]:
for i, desc in enumerate(templates):
    print("=" * 100)
    print(i)
    print(desc[:250])

====================================================================================================
0
Implemented streaming data pipelines on Kafka and Spark Streaming for a real-time user-activity processing platform. Designed the schema-registry integration, the watermark/state management approach, and the deduplication logic for late-arriving even
====================================================================================================
1
Built and maintained data pipelines on Apache Airflow processing ~500GB of daily transactional data across 12 source systems. Worked extensively with Spark (PySpark) for batch processing and dbt for the transformation/modeling layer in our Snowflake
====================================================================================================
2
Customer support team lead at a SaaS product. Managed a team of 8 support agents handling tier-1 and tier-2 tickets; owned the escalation process to engineering and the customer-feedback loop to product. Built out the support knowledge base and the a
====================================================================================================
3
Mechanical engineering design role at a hardware-product company. Led the design of two product subsystems through full lifecycle: concept, DFM/DFMA review, prototype, production tooling. Comfortable with CAD (SolidWorks, Creo), FEA (ANSYS), and the
====================================================================================================
4
Content writing and SEO strategy for a tech-focused publication. Wrote longform articles on developer tools, cloud platforms, and AI/ML topics — including some that ranked on the first page of search for high-competition keywords. Managed a freelance
====================================================================================================
5
Brand design and creative direction at a consumer-products company. Owned brand identity (logo, visual system, typography), packaging design, and digital creative across web and social. Led the recent rebrand and managed a small external agency for p
====================================================================================================
6
Business analyst at a consulting firm, working primarily with retail and CPG clients. Conducted business diagnostics, process re-engineering work, and digital transformation strategy projects. Strong on stakeholder management, structured problem-solv
====================================================================================================
7
Operations management role at a logistics company. Owned daily fulfillment operations across 3 warehouses, managing a team of 80 across receiving, picking, packing, and outbound. Built and tracked the operational KPIs (on-time fulfillment, accuracy,
====================================================================================================
8
Senior accounting role at a mid-sized company — month-end close, financial reporting, statutory compliance (GAAP / Ind-AS), and tax filings. Owned the GL, fixed-asset register, and the audit-readiness function. Managed a team of 3 staff accountants.
====================================================================================================
9
Marketing leadership role at a B2B SaaS company. Owned the demand-generation function — content marketing, paid acquisition, SEO, email nurture. Built and managed a team of 5 across content, performance marketing, and marketing operations. Worked clo
====================================================================================================
10
Enterprise sales of cloud software solutions into the mid-market segment. Carried a $1.8M ARR quota and consistently delivered against it across the last three years. Owned the full sales cycle: prospecting, discovery, technical evaluation (with SE s
====================================================================================================
11
Mixed data science and analytics-engineering role at a marketing-analytics startup. Spent maybe 30% of my time on lightweight ML (clustering, classification, churn prediction in sklearn/XGBoost) and 70% on data infrastructure and dashboards. Comforta
====================================================================================================
12
Android mobile development using Java and (more recently) Kotlin at a consumer-app company. Built and maintained multiple production features including the main shopping flow, push notification system, and the offline-first sync layer. Comfortable wi
====================================================================================================
13
Test automation and QA engineering for a fintech product. Built and maintained the end-to-end test suite using Selenium and pytest, plus the load-testing setup using Locust. Worked closely with developers on testability patterns and with product on a
====================================================================================================
14
Frontend engineering at a media company. React, TypeScript, and the typical surrounding tooling (Webpack, Jest, Cypress). Built the company's design system from scratch and led the migration from a legacy AngularJS app. Strong on the frontend craft —
====================================================================================================
15
Cloud infrastructure and DevOps work at an enterprise SaaS company. Owned the AWS account architecture (VPC, IAM, networking), the Terraform modules for our service deployments, and the Kubernetes cluster operations. Designed the CI/CD pipelines (Git
====================================================================================================
16
Java backend development at a large enterprise — Spring Boot microservices, Kafka for inter-service messaging, Postgres + Redis for storage. Worked on the customer onboarding flow which involved orchestrating multiple downstream services. Solid on th
====================================================================================================
17
Full-stack web application development at a SaaS company. Built React-based admin interfaces and the Node.js REST API backing them. Worked across the stack: frontend components, REST endpoint design, PostgreSQL schema, deployment via Docker/Kubernete
====================================================================================================
18
Trained and shipped multiple ranking models for our product's discovery feed using XGBoost and LightGBM. Designed features across three families: content metadata, user behavior signals, and item engagement history. Owned the offline-online correlati
====================================================================================================
19
Owned the ranking layer for an e-commerce search product, evolving it from a hand-tuned scoring function to a learning-to-rank model over 9 months. Designed the relevance labeling pipeline (mix of click-through data and explicit human judgments), the
====================================================================================================
20
Built NLP pipelines for sentiment analysis and document classification — primarily for an internal feedback-analytics dashboard. Started with sklearn-based bag-of-words models, then moved to transformer-based classifiers (DistilBERT) for the harder c
====================================================================================================
21
Backend + data hybrid role at a growth-stage startup. Built the company's first proper data warehouse (migrating from a tangled set of Postgres replicas to a clean Snowflake setup with dbt), the orchestration layer (Airflow), and the BI integration (
====================================================================================================
22
Designed and maintained the analytical data warehouse on Snowflake supporting the BI team's ~50 dashboards. Wrote complex SQL — heavy on window functions, CTEs, and incremental modeling patterns via dbt. Worked on the data modeling side (dimensional
====================================================================================================
23
Built computer vision models for our product's image moderation feature using PyTorch — fine-tuned ResNet variants on a labeled dataset of ~200K images. Set up the training pipeline (data loading, augmentation, evaluation) and the inference service.
====================================================================================================
24
Contributed to ML feature engineering and model deployment for a fraud-detection product. My main role was engineering: building the Flask-based prediction API, integrating with the feature store, and writing the model-serving observability layer. I
====================================================================================================
25
Backend development with Python (FastAPI), PostgreSQL, and Redis at a B2B SaaS product. Owned the analytics-and-reporting service which serves dashboards to ~3K paying customers. Recent work includes integrating a model-serving service (built by anot
====================================================================================================
26
Worked on customer-facing predictive modeling for an e-commerce platform — churn prediction, conversion likelihood, lifetime value estimation. Used scikit-learn and XGBoost; main models were gradient-boosted trees with ~80 hand-engineered features. T
====================================================================================================
27
Built recommendation-style features at a mid-stage startup — lighter weight than ranking systems at FAANG, but production. Used a combination of collaborative filtering (matrix factorization in implicit-feedback library) and gradient-boosted re-ranki
====================================================================================================
28
Worked on time-series forecasting models for supply-chain demand prediction at a logistics company. Built models in Prophet, LightGBM, and (for one project) a small LSTM — the LightGBM model ended up shipping. Also ran some reinforcement learning exp
====================================================================================================
29
Developed a semantic search feature for an internal knowledge base of ~500K documents. Used sentence-transformers (all-MiniLM-L6-v2 initially, later upgraded to bge-base) with FAISS for fast nearest-neighbor retrieval. Designed the query expansion mo
====================================================================================================
30
Built a content recommendation system serving 10M+ users that combined collaborative filtering with content-based ranking. The system uses item-item similarity (via sentence-transformer embeddings) for cold starts and a gradient-boosted model trained
====================================================================================================
31
Built and shipped a production recommendation system at a marketplace product, going from offline experimentation to live A/B test in 5 months. The system combined collaborative filtering (matrix factorization), content-based features (TF-IDF + sente
====================================================================================================
32
Fine-tuned LLaMA-2-7B and Mistral-7B variants using LoRA and QLoRA for domain-specific candidate-JD matching. Built the data curation pipeline that generated 200K high-quality preference pairs from recruiter labels, plus the eval harness using both r
====================================================================================================
33
Built a RAG-based ranking pipeline serving 50M+ queries per month for an internal recruiter-facing search product. The architecture combined BM25 + dense retrieval (BGE embeddings, FAISS HNSW) with an LLM-based re-ranker on the top-50, falling back t
====================================================================================================
34
Led the engineering team building infrastructure to surface relevant content to users at scale. The system processed billions of documents and served millions of queries with low latency. Most of the technical effort went into the boring-but-essentia
====================================================================================================
35
Built systems that understand what users are looking for and connect them to the most relevant matches across a large dataset. Worked at the intersection of infrastructure, algorithms, and product judgment — none of the three were optional. Recent pr
====================================================================================================
36
Implemented a RAG-based customer support chatbot integrated with our existing ticketing system. Built the document ingestion pipeline (chunking, embedding via OpenAI embeddings, storing in Pinecone) and the answer-generation layer (initially GPT-4, t
====================================================================================================
37
Built and operated production ML pipelines using MLflow for experiment tracking, Kubeflow for orchestration, and our internal feature store. My main project was a churn prediction model that's now used by the customer success team to prioritize outre
====================================================================================================
38
Owned the search and discovery experience end-to-end at a consumer product, from how content is represented internally through to how the most relevant results appear for each user's intent. The work spanned data infrastructure, ranking algorithms, e
====================================================================================================
39
Shipped the personalization infrastructure: the system that learns from user behavior and improves relevance over time. Designed the offline experimentation environment, the online A/B testing framework, and the feature-engineering pipeline that conn
====================================================================================================
40
Owned the end-to-end ranking pipeline at a recommendations-heavy consumer product: candidate sourcing → embedding generation (using a fine-tuned BGE-large) → Pinecone retrieval → learning-to-rank re-scoring (XGBoost) → behavioral-signal integration.
====================================================================================================
41
Owned the design and rollout of a large-scale semantic search system serving an internal corpus of 35M+ items. Migrated the existing BM25-only retrieval to a hybrid setup combining sparse and dense vectors (sentence-transformers, MPNet-base initially
====================================================================================================
42
Designed the ranking layer for the company's flagship product: how do we surface the right thing at the right time, across millions of items, for millions of users. The hard problem was rarely the modeling — it was the data pipeline that fed the mode
====================================================================================================
43
Led the migration from keyword-based to embedding-based search across a 30M+ candidate corpus over 8 months. Designed three successive ranker variants and ran them in A/B testing alongside the legacy keyword system. The final embedding ranker improve

In [ ]:
for i, desc in enumerate(templates):
    print("=" * 100)
    print(i)
    print(desc[:250])

====================================================================================================
0
Implemented streaming data pipelines on Kafka and Spark Streaming for a real-time user-activity processing platform. Designed the schema-registry integration, the watermark/state management approach, and the deduplication logic for late-arriving even
====================================================================================================
1
Built and maintained data pipelines on Apache Airflow processing ~500GB of daily transactional data across 12 source systems. Worked extensively with Spark (PySpark) for batch processing and dbt for the transformation/modeling layer in our Snowflake
====================================================================================================
2
Customer support team lead at a SaaS product. Managed a team of 8 support agents handling tier-1 and tier-2 tickets; owned the escalation process to engineering and the customer-feedback loop to product. Built out the support knowledge base and the a
====================================================================================================
3
Mechanical engineering design role at a hardware-product company. Led the design of two product subsystems through full lifecycle: concept, DFM/DFMA review, prototype, production tooling. Comfortable with CAD (SolidWorks, Creo), FEA (ANSYS), and the
====================================================================================================
4
Content writing and SEO strategy for a tech-focused publication. Wrote longform articles on developer tools, cloud platforms, and AI/ML topics — including some that ranked on the first page of search for high-competition keywords. Managed a freelance
====================================================================================================
5
Brand design and creative direction at a consumer-products company. Owned brand identity (logo, visual system, typography), packaging design, and digital creative across web and social. Led the recent rebrand and managed a small external agency for p
====================================================================================================
6
Business analyst at a consulting firm, working primarily with retail and CPG clients. Conducted business diagnostics, process re-engineering work, and digital transformation strategy projects. Strong on stakeholder management, structured problem-solv
====================================================================================================
7
Operations management role at a logistics company. Owned daily fulfillment operations across 3 warehouses, managing a team of 80 across receiving, picking, packing, and outbound. Built and tracked the operational KPIs (on-time fulfillment, accuracy,
====================================================================================================
8
Senior accounting role at a mid-sized company — month-end close, financial reporting, statutory compliance (GAAP / Ind-AS), and tax filings. Owned the GL, fixed-asset register, and the audit-readiness function. Managed a team of 3 staff accountants.
====================================================================================================
9
Marketing leadership role at a B2B SaaS company. Owned the demand-generation function — content marketing, paid acquisition, SEO, email nurture. Built and managed a team of 5 across content, performance marketing, and marketing operations. Worked clo
====================================================================================================
10
Enterprise sales of cloud software solutions into the mid-market segment. Carried a $1.8M ARR quota and consistently delivered against it across the last three years. Owned the full sales cycle: prospecting, discovery, technical evaluation (with SE s
====================================================================================================
11
Mixed data science and analytics-engineering role at a marketing-analytics startup. Spent maybe 30% of my time on lightweight ML (clustering, classification, churn prediction in sklearn/XGBoost) and 70% on data infrastructure and dashboards. Comforta
====================================================================================================
12
Android mobile development using Java and (more recently) Kotlin at a consumer-app company. Built and maintained multiple production features including the main shopping flow, push notification system, and the offline-first sync layer. Comfortable wi
====================================================================================================
13
Test automation and QA engineering for a fintech product. Built and maintained the end-to-end test suite using Selenium and pytest, plus the load-testing setup using Locust. Worked closely with developers on testability patterns and with product on a
====================================================================================================
14
Frontend engineering at a media company. React, TypeScript, and the typical surrounding tooling (Webpack, Jest, Cypress). Built the company's design system from scratch and led the migration from a legacy AngularJS app. Strong on the frontend craft —
====================================================================================================
15
Cloud infrastructure and DevOps work at an enterprise SaaS company. Owned the AWS account architecture (VPC, IAM, networking), the Terraform modules for our service deployments, and the Kubernetes cluster operations. Designed the CI/CD pipelines (Git
====================================================================================================
16
Java backend development at a large enterprise — Spring Boot microservices, Kafka for inter-service messaging, Postgres + Redis for storage. Worked on the customer onboarding flow which involved orchestrating multiple downstream services. Solid on th
====================================================================================================
17
Full-stack web application development at a SaaS company. Built React-based admin interfaces and the Node.js REST API backing them. Worked across the stack: frontend components, REST endpoint design, PostgreSQL schema, deployment via Docker/Kubernete
====================================================================================================
18
Trained and shipped multiple ranking models for our product's discovery feed using XGBoost and LightGBM. Designed features across three families: content metadata, user behavior signals, and item engagement history. Owned the offline-online correlati
====================================================================================================
19
Owned the ranking layer for an e-commerce search product, evolving it from a hand-tuned scoring function to a learning-to-rank model over 9 months. Designed the relevance labeling pipeline (mix of click-through data and explicit human judgments), the
====================================================================================================
20
Built NLP pipelines for sentiment analysis and document classification — primarily for an internal feedback-analytics dashboard. Started with sklearn-based bag-of-words models, then moved to transformer-based classifiers (DistilBERT) for the harder c
====================================================================================================
21
Backend + data hybrid role at a growth-stage startup. Built the company's first proper data warehouse (migrating from a tangled set of Postgres replicas to a clean Snowflake setup with dbt), the orchestration layer (Airflow), and the BI integration (
====================================================================================================
22
Designed and maintained the analytical data warehouse on Snowflake supporting the BI team's ~50 dashboards. Wrote complex SQL — heavy on window functions, CTEs, and incremental modeling patterns via dbt. Worked on the data modeling side (dimensional
====================================================================================================
23
Built computer vision models for our product's image moderation feature using PyTorch — fine-tuned ResNet variants on a labeled dataset of ~200K images. Set up the training pipeline (data loading, augmentation, evaluation) and the inference service.
====================================================================================================
24
Contributed to ML feature engineering and model deployment for a fraud-detection product. My main role was engineering: building the Flask-based prediction API, integrating with the feature store, and writing the model-serving observability layer. I
====================================================================================================
25
Backend development with Python (FastAPI), PostgreSQL, and Redis at a B2B SaaS product. Owned the analytics-and-reporting service which serves dashboards to ~3K paying customers. Recent work includes integrating a model-serving service (built by anot
====================================================================================================
26
Worked on customer-facing predictive modeling for an e-commerce platform — churn prediction, conversion likelihood, lifetime value estimation. Used scikit-learn and XGBoost; main models were gradient-boosted trees with ~80 hand-engineered features. T
====================================================================================================
27
Built recommendation-style features at a mid-stage startup — lighter weight than ranking systems at FAANG, but production. Used a combination of collaborative filtering (matrix factorization in implicit-feedback library) and gradient-boosted re-ranki
====================================================================================================
28
Worked on time-series forecasting models for supply-chain demand prediction at a logistics company. Built models in Prophet, LightGBM, and (for one project) a small LSTM — the LightGBM model ended up shipping. Also ran some reinforcement learning exp
====================================================================================================
29
Developed a semantic search feature for an internal knowledge base of ~500K documents. Used sentence-transformers (all-MiniLM-L6-v2 initially, later upgraded to bge-base) with FAISS for fast nearest-neighbor retrieval. Designed the query expansion mo
====================================================================================================
30
Built a content recommendation system serving 10M+ users that combined collaborative filtering with content-based ranking. The system uses item-item similarity (via sentence-transformer embeddings) for cold starts and a gradient-boosted model trained
====================================================================================================
31
Built and shipped a production recommendation system at a marketplace product, going from offline experimentation to live A/B test in 5 months. The system combined collaborative filtering (matrix factorization), content-based features (TF-IDF + sente
====================================================================================================
32
Fine-tuned LLaMA-2-7B and Mistral-7B variants using LoRA and QLoRA for domain-specific candidate-JD matching. Built the data curation pipeline that generated 200K high-quality preference pairs from recruiter labels, plus the eval harness using both r
====================================================================================================
33
Built a RAG-based ranking pipeline serving 50M+ queries per month for an internal recruiter-facing search product. The architecture combined BM25 + dense retrieval (BGE embeddings, FAISS HNSW) with an LLM-based re-ranker on the top-50, falling back t
====================================================================================================
34
Led the engineering team building infrastructure to surface relevant content to users at scale. The system processed billions of documents and served millions of queries with low latency. Most of the technical effort went into the boring-but-essentia
====================================================================================================
35
Built systems that understand what users are looking for and connect them to the most relevant matches across a large dataset. Worked at the intersection of infrastructure, algorithms, and product judgment — none of the three were optional. Recent pr
====================================================================================================
36
Implemented a RAG-based customer support chatbot integrated with our existing ticketing system. Built the document ingestion pipeline (chunking, embedding via OpenAI embeddings, storing in Pinecone) and the answer-generation layer (initially GPT-4, t
====================================================================================================
37
Built and operated production ML pipelines using MLflow for experiment tracking, Kubeflow for orchestration, and our internal feature store. My main project was a churn prediction model that's now used by the customer success team to prioritize outre
====================================================================================================
38
Owned the search and discovery experience end-to-end at a consumer product, from how content is represented internally through to how the most relevant results appear for each user's intent. The work spanned data infrastructure, ranking algorithms, e
====================================================================================================
39
Shipped the personalization infrastructure: the system that learns from user behavior and improves relevance over time. Designed the offline experimentation environment, the online A/B testing framework, and the feature-engineering pipeline that conn
====================================================================================================
40
Owned the end-to-end ranking pipeline at a recommendations-heavy consumer product: candidate sourcing → embedding generation (using a fine-tuned BGE-large) → Pinecone retrieval → learning-to-rank re-scoring (XGBoost) → behavioral-signal integration.
====================================================================================================
41
Owned the design and rollout of a large-scale semantic search system serving an internal corpus of 35M+ items. Migrated the existing BM25-only retrieval to a hybrid setup combining sparse and dense vectors (sentence-transformers, MPNet-base initially
====================================================================================================
42
Designed the ranking layer for the company's flagship product: how do we surface the right thing at the right time, across millions of items, for millions of users. The hard problem was rarely the modeling — it was the data pipeline that fed the mode
====================================================================================================
43
Led the migration from keyword-based to embedding-based search across a 30M+ candidate corpus over 8 months. Designed three successive ranker variants and ran them in A/B testing alongside the legacy keyword system. The final embedding ranker improve

In [ ]:
template_score = {

# Tier 5
18:46,
19:46,
29:46,
30:46,
31:46,
33:46,
35:46,
38:46,
39:46,
40:46,
41:46,
42:46,
43:46,

# Tier 4
20:38,
32:38,
36:38,
37:38,

# Tier 3
23:28,
24:28,
26:28,
27:28,
28:28,

# Tier 2
0:15,
1:15,
11:15,
21:15,
22:15,
25:15,

# Tier 1
14:5,
15:5,
16:5,
17:5,

# Tier 0
2:0,
3:0,
4:0,
5:0,
6:0,
7:0,
8:0,
9:0,
10:0,
12:0,
13:0

}

In [ ]:
tech_weights = {
    "faiss": 5,
    "pinecone": 4,
    "milvus": 4,
    "bm25": 5,
    "semantic search": 5,
    "dense retrieval": 5,
    "recommendation": 4,
    "ranking": 4,
    "learning-to-rank": 4,
    "rag": 3,
    "embedding": 3,
    "bge": 3,
    "llm": 2,
    "xgboost": 2,
    "lightgbm": 2
}

In [ ]:
template_to_score = {}

for i, desc in enumerate(templates):
    template_to_score[desc] = template_score.get(i, 0)

In [ ]:
career_scores = []

for r in records:

    score = 0

    for job in r["career_history"]:

        desc = job["description"].lower()

        # Existing template score
        score += template_to_score.get(job["description"], 0)

        # Technology bonus
        for tech, wt in tech_weights.items():
            if tech in desc:
                score += wt

    career_scores.append(
        (
            r["candidate_id"],
            r["profile"]["current_title"],
            score
        )
    )

In [ ]:
career_df = pd.DataFrame(

    career_scores,

    columns=[

        "candidate_id",

        "title",

        "career"

    ]

)

career_df.head()

   candidate_id               title  career
0  CAND_0000001    Backend Engineer      30
1  CAND_0000002  Operations Manager       2
2  CAND_0000003    Customer Support       0
3  CAND_0000004   Marketing Manager       4
4  CAND_0000005          Accountant       0

In [ ]:
career_df.sort_values(

    "career",

    ascending=False

).head(20)

       candidate_id                             title  career
30952  CAND_0030953                   Search Engineer     277
7411   CAND_0007412               Applied ML Engineer     252
10769  CAND_0010770   Recommendation Systems Engineer     236
55991  CAND_0055992                       AI Engineer     223
77336  CAND_0077337   Staff Machine Learning Engineer     223
83306  CAND_0083307                   Search Engineer     220
65877  CAND_0065878             Senior Data Scientist     219
30     CAND_0000031   Recommendation Systems Engineer     216
39753  CAND_0039754          Senior Applied Scientist     212
19479  CAND_0019480                      NLP Engineer     210
10684  CAND_0010685                      NLP Engineer     210
64325  CAND_0064326                   Search Engineer     210
80765  CAND_0080766   Staff Machine Learning Engineer     208
79386  CAND_0079387                       AI Engineer     207
5648   CAND_0005649             Senior Data Scientist     204
44882  CAND_0044883                       AI Engineer     204
18498  CAND_0018499  Senior Machine Learning Engineer     202
68810  CAND_0068811               Applied ML Engineer     197
41610  CAND_0041611   Staff Machine Learning Engineer     194
92277  CAND_0092278               Senior NLP Engineer     194

In [ ]:
career_df = pd.DataFrame(

    career_scores,

    columns=[

        "candidate_id",

        "title",

        "career"

    ]

)

career_df.head()

   candidate_id               title  career
0  CAND_0000001    Backend Engineer      30
1  CAND_0000002  Operations Manager       2
2  CAND_0000003    Customer Support       0
3  CAND_0000004   Marketing Manager       4
4  CAND_0000005          Accountant       0

In [ ]:
career_df["career"].describe()

count    100000.000000
mean          5.920320
std          12.429765
min           0.000000
25%           0.000000
50%           2.000000
75%           5.000000
max         277.000000
Name: career, dtype: float64

In [ ]:
career_df.sort_values(

    "career",

    ascending=False

).head(10)

       candidate_id                            title  career
30952  CAND_0030953                  Search Engineer     277
7411   CAND_0007412              Applied ML Engineer     252
10769  CAND_0010770  Recommendation Systems Engineer     236
55991  CAND_0055992                      AI Engineer     223
77336  CAND_0077337  Staff Machine Learning Engineer     223
83306  CAND_0083307                  Search Engineer     220
65877  CAND_0065878            Senior Data Scientist     219
30     CAND_0000031  Recommendation Systems Engineer     216
39753  CAND_0039754         Senior Applied Scientist     212
19479  CAND_0019480                     NLP Engineer     210

In [ ]:
keywords = [

    "recommendation",
    "ranking",
    "search",
    "semantic",
    "retrieval",
    "embedding",
    "embeddings",
    "faiss",
    "pinecone",
    "milvus",
    "bm25",
    "rag",
    "llm",
    "lora",
    "qlora",
    "transformer",
    "sentence-transformers",
    "bge",
    "xgboost",
    "lightgbm",
    "learning-to-rank",
    "collaborative filtering"

]

In [ ]:
import time

start = time.time()

keyword_scores = []
keywords_lower = [k.lower() for k in keywords]

for r in records:
    text = " ".join(
        (job.get("description", "") or "").lower()
        for job in r.get("career_history", [])
    )

    score = sum(k in text for k in keywords_lower)

    keyword_scores.append(
        (
            r["candidate_id"],
            r["profile"]["current_title"],
            score
        )
    )

print("Time:", time.time() - start)

Time: 3.9921786785125732

In [ ]:
keyword_weights = {
    "semantic search": 5,
    "dense retrieval": 5,
    "faiss": 5,
    "bm25": 5,
    "bge": 5,

    "recommendation": 4,
    "ranking": 4,
    "learning-to-rank": 4,
    "pinecone": 4,
    "milvus": 4,

    "rag": 3,
    "embedding": 3,
    "sentence-transformer": 3,
    "lora": 3,
    "qlora": 3,
    "llama": 3,

    "xgboost": 2,
    "lightgbm": 2
}

In [ ]:
keyword_scores = []

for r in records:

    text = " ".join(
        job["description"].lower()
        for job in r["career_history"]
    )

    score = 0

    for kw, weight in keyword_weights.items():

        if kw in text:
            score += weight

    keyword_scores.append(
        (
            r["candidate_id"],
            r["profile"]["current_title"],
            score
        )
    )

In [ ]:
keyword_df = pd.DataFrame(

    keyword_scores,

    columns=[

        "candidate_id",

        "title",

        "keyword"

    ]

)

keyword_df.head()

   candidate_id               title  keyword
0  CAND_0000001    Backend Engineer        0
1  CAND_0000002  Operations Manager        0
2  CAND_0000003    Customer Support        0
3  CAND_0000004   Marketing Manager        0
4  CAND_0000005          Accountant        0

In [ ]:
keyword_df["keyword_n"] = (
    keyword_df["keyword"] /
    keyword_df["keyword"].max()
)

In [ ]:
keyword_df.sort_values(

    "keyword",

    ascending=False

).head(20)

       candidate_id                             title  keyword  keyword_n
46063  CAND_0046064               Senior NLP Engineer       53   1.000000
39753  CAND_0039754          Senior Applied Scientist       52   0.981132
55904  CAND_0055905  Senior Machine Learning Engineer       51   0.962264
8424   CAND_0008425               Senior NLP Engineer       48   0.905660
55991  CAND_0055992                       AI Engineer       45   0.849057
30952  CAND_0030953                   Search Engineer       45   0.849057
92277  CAND_0092278               Senior NLP Engineer       44   0.830189
5259   CAND_0005260               Senior NLP Engineer       43   0.811321
18498  CAND_0018499  Senior Machine Learning Engineer       43   0.811321
41610  CAND_0041611   Staff Machine Learning Engineer       42   0.792453
81845  CAND_0081846                  Lead AI Engineer       42   0.792453
5648   CAND_0005649             Senior Data Scientist       41   0.773585
28792  CAND_0028793                   Search Engineer       41   0.773585
91533  CAND_0091534                       AI Engineer       41   0.773585
44882  CAND_0044883                       AI Engineer       41   0.773585
79386  CAND_0079387                       AI Engineer       41   0.773585
83306  CAND_0083307                   Search Engineer       41   0.773585
51291  CAND_0051292               Applied ML Engineer       41   0.773585
44854  CAND_0044855             Senior Data Scientist       41   0.773585
1609   CAND_0001610         Machine Learning Engineer       38   0.716981

In [ ]:
keyword_df["keyword"].describe()

count    100000.000000
mean          0.368100
std           1.475162
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max          53.000000
Name: keyword, dtype: float64

In [ ]:
behavior_scores = []

for r in records:

    signal = r["redrob_signals"]

    response = signal["recruiter_response_rate"]
    github = signal["github_activity_score"]
    notice = signal["notice_period_days"]
    open_to_work = signal["open_to_work_flag"]

    behavior_scores.append((
        r["candidate_id"],
        response,
        github,
        notice,
        open_to_work
    ))

In [ ]:
print(records[0]["redrob_signals"].keys())

dict_keys(['profile_completeness_score', 'signup_date', 'last_active_date', 'open_to_work_flag', 'profile_views_received_30d', 'applications_submitted_30d', 'recruiter_response_rate', 'avg_response_time_hours', 'skill_assessment_scores', 'connection_count', 'endorsements_received', 'notice_period_days', 'expected_salary_range_inr_lpa', 'preferred_work_mode', 'willing_to_relocate', 'github_activity_score', 'search_appearance_30d', 'saved_by_recruiters_30d', 'interview_completion_rate', 'offer_acceptance_rate', 'verified_email', 'verified_phone', 'linkedin_connected'])

In [ ]:
behavior_df = pd.DataFrame(

    behavior_scores,

    columns=[
        "candidate_id",
        "response",
        "github",
        "notice",
        "open"
    ]

)

In [ ]:
behavior_df["response_n"] = behavior_df["response"]

behavior_df["github_n"] = (
    behavior_df["github"] /
    behavior_df["github"].max()
)

behavior_df["notice_n"] = (
    behavior_df["notice"].max() -
    behavior_df["notice"]
) / behavior_df["notice"].max()

behavior_df["open_n"] = behavior_df["open"].astype(int)

In [ ]:
behavior_df.columns.tolist()

['candidate_id',
 'response',
 'github',
 'notice',
 'open',
 'response_n',
 'github_n',
 'notice_n',
 'open_n']

In [ ]:
behavior_df["behavior"] = (
      0.40 * behavior_df["response_n"]
    + 0.20 * behavior_df["github_n"]
    + 0.20 * behavior_df["notice_n"]
    + 0.20 * behavior_df["open_n"]
)

In [ ]:
behavior_df.columns.tolist()

['candidate_id',
 'response',
 'github',
 'notice',
 'open',
 'response_n',
 'github_n',
 'notice_n',
 'open_n',
 'behavior']

In [ ]:
final_df = career_df.merge(
    keyword_df[["candidate_id", "keyword", "keyword_n"]],
    on="candidate_id"
)

final_df = final_df.merge(
    behavior_df[["candidate_id", "behavior"]],
    on="candidate_id"
)

final_df = final_df.merge(
    skill_df[["candidate_id", "skill", "skill_n"]],
    on="candidate_id"
)

print(final_df.shape)
final_df.head()

NameError: name 'skill_df' is not defined

In [ ]:
behavior_df.head()

,candidate_id,response,github,notice,open,response_n,github_n,notice_n,open_n,behavior
0,CAND_0000001,0.34,9.2,60,True,0.34,0.094943,0.6,1,0.474989
1,CAND_0000002,0.29,-1.0,60,True,0.29,-0.010320,0.6,1,0.433936
2,CAND_0000003,0.46,-1.0,150,False,0.46,-0.010320,0.0,0,0.181936
3,CAND_0000004,0.26,-1.0,120,False,0.26,-0.010320,0.2,0,0.141936
4,CAND_0000005,0.37,-1.0,30,True,0.37,-0.010320,0.8,1,0.505936

In [ ]:
behavior_df["github"] = behavior_df["github"].clip(lower=0)

In [ ]:
behavior_df["github"] = behavior_df["github"].replace(-1, 0)

In [ ]:
behavior_df["github_n"] = (
    behavior_df["github"] /
    behavior_df["github"].max()
)

In [ ]:
rare_skills = [
    "faiss",
    "pinecone",
    "milvus",
    "embedding",
    "recommendation",
    "lora",
    "qlora",
    "rag",
    "bm25",
    "transformer",
    "sentence",
    "bge",
    "vector"
]

In [ ]:
skill_bonus = []

for r in records:

    score = 0

    for skill in r["skills"]:

        name = skill["name"].lower()

        for rs in rare_skills:

            if rs in name:
                score += 1
                break

    skill_bonus.append(
        (
            r["candidate_id"],
            score
        )
    )

In [ ]:
skill_df = pd.DataFrame(

    skill_bonus,

    columns=[

        "candidate_id",

        "skill"

    ]
)

skill_df.head()

   candidate_id  skill
0  CAND_0000001      2
1  CAND_0000002      0
2  CAND_0000003      0
3  CAND_0000004      0
4  CAND_0000005      0

In [ ]:
skill_df["skill_n"] = (
    skill_df["skill"] /
    skill_df["skill"].max()
)

In [ ]:
final_df = career_df.merge(
    keyword_df[["candidate_id", "keyword", "keyword_n"]],
    on="candidate_id",
    how="inner"
)

final_df = final_df.merge(
    behavior_df[["candidate_id", "behavior"]],
    on="candidate_id",
    how="inner"
)

final_df = final_df.merge(
    skill_df[["candidate_id", "skill", "skill_n"]],
    on="candidate_id",
    how="inner"
)

print(final_df.shape)
final_df.head()

(100000, 8)

,candidate_id,title,career,keyword,keyword_n,behavior,skill,skill_n
0,CAND_0000001,Backend Engineer,30,0,0.0,0.474989,2,0.25
1,CAND_0000002,Operations Manager,2,0,0.0,0.433936,0,0.00
2,CAND_0000003,Customer Support,0,0,0.0,0.181936,0,0.00
3,CAND_0000004,Marketing Manager,4,0,0.0,0.141936,0,0.00
4,CAND_0000005,Accountant,0,0,0.0,0.505936,0,0.00

In [ ]:
skill_df["skill"].describe()

count    100000.000000
mean          0.475250
std           1.336677
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           8.000000
Name: skill, dtype: float64

In [ ]:
career_df["career_n"] = career_df["career"] / career_df["career"].max()

keyword_df["keyword_n"] = keyword_df["keyword"] / keyword_df["keyword"].max()

skill_df["skill_n"] = skill_df["skill"] / skill_df["skill"].max()

In [ ]:
career_df.columns.tolist()

['candidate_id', 'title', 'career', 'career_n']

In [ ]:
final_df["final_score"] = (
      0.50 * final_df["career_n"]
    + 0.30 * final_df["keyword_n"]
    + 0.10 * final_df["behavior"]
    + 0.10 * final_df["skill_n"]
)

In [ ]:
print(final_df.columns.tolist())

['candidate_id', 'title', 'career', 'keyword', 'keyword_n', 'behavior', 'skill', 'skill_n']

In [ ]:
career_df.columns.tolist()

['candidate_id', 'title', 'career', 'career_n']

In [ ]:
final_df = career_df.merge(
    keyword_df[["candidate_id", "keyword", "keyword_n"]],
    on="candidate_id",
    how="inner"
)

final_df = final_df.merge(
    behavior_df[["candidate_id", "behavior"]],
    on="candidate_id",
    how="inner"
)

final_df = final_df.merge(
    skill_df[["candidate_id", "skill", "skill_n"]],
    on="candidate_id",
    how="inner"
)

print(final_df.columns.tolist())

['candidate_id', 'title', 'career', 'career_n', 'keyword', 'keyword_n', 'behavior', 'skill', 'skill_n']

In [ ]:
top100 = (
    final_df
    .sort_values("final_score", ascending=False)
    .reset_index(drop=True)
)

top100.head(20)

,candidate_id,title,career,career_n,keyword,keyword_n,behavior,skill,skill_n,final_score
0,CAND_0030953,Search Engineer,277,1.000000,45,0.849057,0.435344,3,0.375,0.835751
1,CAND_0039754,Senior Applied Scientist,212,0.765343,52,0.981132,0.843959,2,0.250,0.786407
2,CAND_0055992,AI Engineer,223,0.805054,45,0.849057,0.742778,4,0.500,0.781522
3,CAND_0018499,Senior Machine Learning Engineer,202,0.729242,43,0.811321,0.819666,7,0.875,0.777484
4,CAND_0077337,Staff Machine Learning Engineer,223,0.805054,35,0.660377,0.840351,7,0.875,0.772175
5,CAND_0046064,Senior NLP Engineer,192,0.693141,53,1.000000,0.810906,3,0.375,0.765161
6,CAND_0079387,AI Engineer,207,0.747292,41,0.773585,0.816301,6,0.750,0.762352
7,CAND_0083307,Search Engineer,220,0.794224,41,0.773585,0.662828,5,0.625,0.757970
8,CAND_0055905,Senior Machine Learning Engineer,184,0.664260,51,0.962264,0.705936,3,0.375,0.728903
9,CAND_0010770,Recommendation Systems Engineer,236,0.851986,35,0.660377,0.649936,2,0.250,0.714100
10,CAND_0008425,Senior NLP Engineer,174,0.628159,48,0.905660,0.654010,5,0.625,0.713679
11,CAND_0005649,Senior Data Scientist,204,0.736462,41,0.773585,0.674563,3,0.375,0.705263
12,CAND_0007412,Applied ML Engineer,252,0.909747,22,0.415094,0.618303,5,0.625,0.703732
13,CAND_0044883,AI Engineer,204,0.736462,41,0.773585,0.561511,3,0.375,0.693958
14,CAND_0071974,Senior AI Engineer,169,0.610108,38,0.716981,0.814898,6,0.750,0.676638
15,CAND_0088025,Staff Machine Learning Engineer,192,0.693141,29,0.547170,0.765973,7,0.875,0.674819
16,CAND_0092278,Senior NLP Engineer,194,0.700361,44,0.830189,0.105936,5,0.625,0.672331
17,CAND_0029367,Senior Data Scientist,176,0.635379,33,0.622642,0.670147,7,0.875,0.658997
18,CAND_0010685,NLP Engineer,210,0.758123,35,0.660377,0.689936,1,0.125,0.658668
19,CAND_0041611,Staff Machine Learning Engineer,194,0.700361,42,0.792453,0.185936,4,0.500,0.656510

In [ ]:
top100 = (
    final_df
    .sort_values("final_score", ascending=False)
    .head(100)
)

top100[
    [
        "candidate_id",
        "title",
        "career",
        "keyword",
        "behavior",
        "skill",
        "final_score"
    ]
].head(20)

,candidate_id,title,career,keyword,behavior,skill,final_score
30952,CAND_0030953,Search Engineer,277,45,0.435344,3,0.835751
39753,CAND_0039754,Senior Applied Scientist,212,52,0.843959,2,0.786407
55991,CAND_0055992,AI Engineer,223,45,0.742778,4,0.781522
18498,CAND_0018499,Senior Machine Learning Engineer,202,43,0.819666,7,0.777484
77336,CAND_0077337,Staff Machine Learning Engineer,223,35,0.840351,7,0.772175
46063,CAND_0046064,Senior NLP Engineer,192,53,0.810906,3,0.765161
79386,CAND_0079387,AI Engineer,207,41,0.816301,6,0.762352
83306,CAND_0083307,Search Engineer,220,41,0.662828,5,0.757970
55904,CAND_0055905,Senior Machine Learning Engineer,184,51,0.705936,3,0.728903
10769,CAND_0010770,Recommendation Systems Engineer,236,35,0.649936,2,0.714100
8424,CAND_0008425,Senior NLP Engineer,174,48,0.654010,5,0.713679
5648,CAND_0005649,Senior Data Scientist,204,41,0.674563,3,0.705263
7411,CAND_0007412,Applied ML Engineer,252,22,0.618303,5,0.703732
44882,CAND_0044883,AI Engineer,204,41,0.561511,3,0.693958
71973,CAND_0071974,Senior AI Engineer,169,38,0.814898,6,0.676638
88024,CAND_0088025,Staff Machine Learning Engineer,192,29,0.765973,7,0.674819
92277,CAND_0092278,Senior NLP Engineer,194,44,0.105936,5,0.672331
29366,CAND_0029367,Senior Data Scientist,176,33,0.670147,7,0.658997
10684,CAND_0010685,NLP Engineer,210,35,0.689936,1,0.658668
41610,CAND_0041611,Staff Machine Learning Engineer,194,42,0.185936,4,0.656510

In [ ]:
top100 = (
    final_df
    .sort_values("final_score", ascending=False)
    .reset_index(drop=True)
)

top100.head(20)

,candidate_id,title,career,career_n,keyword,keyword_n,behavior,skill,skill_n,final_score
0,CAND_0030953,Search Engineer,277,1.000000,45,0.849057,0.435344,3,0.375,0.835751
1,CAND_0039754,Senior Applied Scientist,212,0.765343,52,0.981132,0.843959,2,0.250,0.786407
2,CAND_0055992,AI Engineer,223,0.805054,45,0.849057,0.742778,4,0.500,0.781522
3,CAND_0018499,Senior Machine Learning Engineer,202,0.729242,43,0.811321,0.819666,7,0.875,0.777484
4,CAND_0077337,Staff Machine Learning Engineer,223,0.805054,35,0.660377,0.840351,7,0.875,0.772175
5,CAND_0046064,Senior NLP Engineer,192,0.693141,53,1.000000,0.810906,3,0.375,0.765161
6,CAND_0079387,AI Engineer,207,0.747292,41,0.773585,0.816301,6,0.750,0.762352
7,CAND_0083307,Search Engineer,220,0.794224,41,0.773585,0.662828,5,0.625,0.757970
8,CAND_0055905,Senior Machine Learning Engineer,184,0.664260,51,0.962264,0.705936,3,0.375,0.728903
9,CAND_0010770,Recommendation Systems Engineer,236,0.851986,35,0.660377,0.649936,2,0.250,0.714100
10,CAND_0008425,Senior NLP Engineer,174,0.628159,48,0.905660,0.654010,5,0.625,0.713679
11,CAND_0005649,Senior Data Scientist,204,0.736462,41,0.773585,0.674563,3,0.375,0.705263
12,CAND_0007412,Applied ML Engineer,252,0.909747,22,0.415094,0.618303,5,0.625,0.703732
13,CAND_0044883,AI Engineer,204,0.736462,41,0.773585,0.561511,3,0.375,0.693958
14,CAND_0071974,Senior AI Engineer,169,0.610108,38,0.716981,0.814898,6,0.750,0.676638
15,CAND_0088025,Staff Machine Learning Engineer,192,0.693141,29,0.547170,0.765973,7,0.875,0.674819
16,CAND_0092278,Senior NLP Engineer,194,0.700361,44,0.830189,0.105936,5,0.625,0.672331
17,CAND_0029367,Senior Data Scientist,176,0.635379,33,0.622642,0.670147,7,0.875,0.658997
18,CAND_0010685,NLP Engineer,210,0.758123,35,0.660377,0.689936,1,0.125,0.658668
19,CAND_0041611,Staff Machine Learning Engineer,194,0.700361,42,0.792453,0.185936,4,0.500,0.656510

In [ ]:
top20_ids = top100.head(20)["candidate_id"].tolist()

for r in records:
    if r["candidate_id"] in top20_ids:

        print("=" * 100)
        print(r["candidate_id"])
        print("TITLE :", r["profile"]["current_title"])

        for i, job in enumerate(r["career_history"], 1):
            print(f"\nJob {i}: {job['title']}")
            print(job["description"][:700])

====================================================================================================
CAND_0005649
TITLE : Senior Data Scientist

Job 1: Senior Data Scientist
Developed a semantic search feature for an internal knowledge base of ~500K documents. Used sentence-transformers (all-MiniLM-L6-v2 initially, later upgraded to bge-base) with FAISS for fast nearest-neighbor retrieval. Designed the query expansion module that handles vocabulary mismatch between user queries and document terms. Reported search-relevance improvement of 35% over the prior Elasticsearch BM25 setup, validated through human relevance judgments.

Job 2: Recommendation Systems Engineer
Implemented a RAG-based customer support chatbot integrated with our existing ticketing system. Built the document ingestion pipeline (chunking, embedding via OpenAI embeddings, storing in Pinecone) and the answer-generation layer (initially GPT-4, then a fine-tuned smaller model for cost control). Designed the evaluation framework with both automatic metrics (BLEU, ROUGE) and human-in-the-loop quality scores. Deployment cut average ticket resolution time by 31% for the supported categories.

Job 3: Senior Data Scientist
Built and operated production ML pipelines using MLflow for experiment tracking, Kubeflow for orchestration, and our internal feature store. My main project was a churn prediction model that's now used by the customer success team to prioritize outreach. Designed the model monitoring stack: data drift detection, prediction distribution checks, and alerting. Mentored a junior engineer through their first end-to-end ML project last year.

Job 4: Search Engineer
Trained and shipped multiple ranking models for our product's discovery feed using XGBoost and LightGBM. Designed features across three families: content metadata, user behavior signals, and item engagement history. Owned the offline-online correlation analysis that determined which offline metrics actually predicted A/B test outcomes. Worked closely with PMs to define the optimization target (click-through vs. dwell time vs. downstream conversion) — that work was as important as the modeling itself.
====================================================================================================
CAND_0007412
TITLE : Applied ML Engineer

Job 1: Applied ML Engineer
Implemented a RAG-based customer support chatbot integrated with our existing ticketing system. Built the document ingestion pipeline (chunking, embedding via OpenAI embeddings, storing in Pinecone) and the answer-generation layer (initially GPT-4, then a fine-tuned smaller model for cost control). Designed the evaluation framework with both automatic metrics (BLEU, ROUGE) and human-in-the-loop quality scores. Deployment cut average ticket resolution time by 31% for the supported categories.

Job 2: Recommendation Systems Engineer
Trained and shipped multiple ranking models for our product's discovery feed using XGBoost and LightGBM. Designed features across three families: content metadata, user behavior signals, and item engagement history. Owned the offline-online correlation analysis that determined which offline metrics actually predicted A/B test outcomes. Worked closely with PMs to define the optimization target (click-through vs. dwell time vs. downstream conversion) — that work was as important as the modeling itself.

Job 3: Search Engineer
Implemented a RAG-based customer support chatbot integrated with our existing ticketing system. Built the document ingestion pipeline (chunking, embedding via OpenAI embeddings, storing in Pinecone) and the answer-generation layer (initially GPT-4, then a fine-tuned smaller model for cost control). Designed the evaluation framework with both automatic metrics (BLEU, ROUGE) and human-in-the-loop quality scores. Deployment cut average ticket resolution time by 31% for the supported categories.

Job 4: Machine Learning Engineer
Implemented a RAG-based customer support chatbot integrated with our existing ticketing system. Built the document ingestion pipeline (chunking, embedding via OpenAI embeddings, storing in Pinecone) and the answer-generation layer (initially GPT-4, then a fine-tuned smaller model for cost control). Designed the evaluation framework with both automatic metrics (BLEU, ROUGE) and human-in-the-loop quality scores. Deployment cut average ticket resolution time by 31% for the supported categories.

Job 5: Machine Learning Engineer
Owned the ranking layer for an e-commerce search product, evolving it from a hand-tuned scoring function to a learning-to-rank model over 9 months. Designed the relevance labeling pipeline (mix of click-through data and explicit human judgments), the feature pipeline, and the training/eval workflow. Most of the work was infrastructure and data quality — the modeling part was almost the easy bit. Final model improved revenue-per-search by 12%.
====================================================================================================
CAND_0008425
TITLE : Senior NLP Engineer

Job 1: Senior NLP Engineer
Owned the design and rollout of a large-scale semantic search system serving an internal corpus of 35M+ items. Migrated the existing BM25-only retrieval to a hybrid setup combining sparse and dense vectors (sentence-transformers, MPNet-base initially, later fine-tuned BGE-large for our domain). The new system reduced p95 retrieval latency by 60% while improving NDCG@10 by 18% on our held-out eval set. Spent substantial time on the boring-but-critical parts: incremental index refresh, embedding drift monitoring, online/offline metric correlation. Led a team of 4 engineers across the rollout.

Job 2: Senior ML Engineer — Search & Ranking
Fine-tuned LLaMA-2-7B and Mistral-7B variants using LoRA and QLoRA for domain-specific candidate-JD matching. Built the data curation pipeline that generated 200K high-quality preference pairs from recruiter labels, plus the eval harness using both ranking metrics and human-quality scores. Deployed the model via BentoML on Kubernetes with sub-200ms p95 latency by quantizing to INT8 and batching at the request level. Cost per inference dropped from $0.04 with GPT-3.5-fallback to under $0.001.

Job 3: Lead AI Engineer
Owned the end-to-end ranking pipeline at a recommendations-heavy consumer product: candidate sourcing → embedding generation (using a fine-tuned BGE-large) → Pinecone retrieval → learning-to-rank re-scoring (XGBoost) → behavioral-signal integration. The hardest part wasn't the ML — it was the evaluation: building offline metrics that actually predicted what the recommendation would do to live engagement. After three iterations we landed on a calibration approach using simulated A/B tests that has held up over the last 18 months.
====================================================================================================
CAND_0010685
TITLE : NLP Engineer

Job 1: NLP Engineer
Owned the ranking layer for an e-commerce search product, evolving it from a hand-tuned scoring function to a learning-to-rank model over 9 months. Designed the relevance labeling pipeline (mix of click-through data and explicit human judgments), the feature pipeline, and the training/eval workflow. Most of the work was infrastructure and data quality — the modeling part was almost the easy bit. Final model improved revenue-per-search by 12%.

Job 2: NLP Engineer
Built and operated production ML pipelines using MLflow for experiment tracking, Kubeflow for orchestration, and our internal feature store. My main project was a churn prediction model that's now used by the customer success team to prioritize outreach. Designed the model monitoring stack: data drift detection, prediction distribution checks, and alerting. Mentored a junior engineer through their first end-to-end ML project last year.

Job 3: Machine Learning Engineer
Developed a semantic search feature for an internal knowledge base of ~500K documents. Used sentence-transformers (all-MiniLM-L6-v2 initially, later upgraded to bge-base) with FAISS for fast nearest-neighbor retrieval. Designed the query expansion module that handles vocabulary mismatch between user queries and document terms. Reported search-relevance improvement of 35% over the prior Elasticsearch BM25 setup, validated through human relevance judgments.

Job 4: Search Engineer
Trained and shipped multiple ranking models for our product's discovery feed using XGBoost and LightGBM. Designed features across three families: content metadata, user behavior signals, and item engagement history. Owned the offline-online correlation analysis that determined which offline metrics actually predicted A/B test outcomes. Worked closely with PMs to define the optimization target (click-through vs. dwell time vs. downstream conversion) — that work was as important as the modeling itself.
====================================================================================================
CAND_0010770
TITLE : Recommendation Systems Engineer

Job 1: Recommendation Systems Engineer
Trained and shipped multiple ranking models for our product's discovery feed using XGBoost and LightGBM. Designed features across three families: content metadata, user behavior signals, and item engagement history. Owned the offline-online correlation analysis that determined which offline metrics actually predicted A/B test outcomes. Worked closely with PMs to define the optimization target (click-through vs. dwell time vs. downstream conversion) — that work was as important as the modeling itself.

Job 2: AI Engineer
Developed a semantic search feature for an internal knowledge base of ~500K documents. Used sentence-transformers (all-MiniLM-L6-v2 initially, later upgraded to bge-base) with FAISS for fast nearest-neighbor retrieval. Designed the query expansion module that handles vocabulary mismatch between user queries and document terms. Reported search-relevance improvement of 35% over the prior Elasticsearch BM25 setup, validated through human relevance judgments.

Job 3: Senior Data Scientist
Owned the ranking layer for an e-commerce search product, evolving it from a hand-tuned scoring function to a learning-to-rank model over 9 months. Designed the relevance labeling pipeline (mix of click-through data and explicit human judgments), the feature pipeline, and the training/eval workflow. Most of the work was infrastructure and data quality — the modeling part was almost the easy bit. Final model improved revenue-per-search by 12%.

Job 4: Applied ML Engineer
Developed a semantic search feature for an internal knowledge base of ~500K documents. Used sentence-transformers (all-MiniLM-L6-v2 initially, later upgraded to bge-base) with FAISS for fast nearest-neighbor retrieval. Designed the query expansion module that handles vocabulary mismatch between user queries and document terms. Reported search-relevance improvement of 35% over the prior Elasticsearch BM25 setup, validated through human relevance judgments.
====================================================================================================
CAND_0018499
TITLE : Senior Machine Learning Engineer

Job 1: Senior Machine Learning Engineer
Built a RAG-based ranking pipeline serving 50M+ queries per month for an internal recruiter-facing search product. The architecture combined BM25 + dense retrieval (BGE embeddings, FAISS HNSW) with an LLM-based re-ranker on the top-50, falling back to a learning-to-rank model when latency budget was tight. Designed the offline evaluation framework from scratch — NDCG, MRR, recall@K calibrated against online A/B engagement metrics. Drove the migration over 4 months including the recruiter-feedback loop that surfaced reranking edge cases.

Job 2: Staff Machine Learning Engineer
Built a RAG-based ranking pipeline serving 50M+ queries per month for an internal recruiter-facing search product. The architecture combined BM25 + dense retrieval (BGE embeddings, FAISS HNSW) with an LLM-based re-ranker on the top-50, falling back to a learning-to-rank model when latency budget was tight. Designed the offline evaluation framework from scratch — NDCG, MRR, recall@K calibrated against online A/B engagement metrics. Drove the migration over 4 months including the recruiter-feedback loop that surfaced reranking edge cases.

Job 3: Senior Machine Learning Engineer
Fine-tuned LLaMA-2-7B and Mistral-7B variants using LoRA and QLoRA for domain-specific candidate-JD matching. Built the data curation pipeline that generated 200K high-quality preference pairs from recruiter labels, plus the eval harness using both ranking metrics and human-quality scores. Deployed the model via BentoML on Kubernetes with sub-200ms p95 latency by quantizing to INT8 and batching at the request level. Cost per inference dropped from $0.04 with GPT-3.5-fallback to under $0.001.
====================================================================================================
CAND_0029367
TITLE : Senior Data Scientist

Job 1: Senior Data Scientist
Developed a semantic search feature for an internal knowledge base of ~500K documents. Used sentence-transformers (all-MiniLM-L6-v2 initially, later upgraded to bge-base) with FAISS for fast nearest-neighbor retrieval. Designed the query expansion module that handles vocabulary mismatch between user queries and document terms. Reported search-relevance improvement of 35% over the prior Elasticsearch BM25 setup, validated through human relevance judgments.

Job 2: Applied ML Engineer
Developed a semantic search feature for an internal knowledge base of ~500K documents. Used sentence-transformers (all-MiniLM-L6-v2 initially, later upgraded to bge-base) with FAISS for fast nearest-neighbor retrieval. Designed the query expansion module that handles vocabulary mismatch between user queries and document terms. Reported search-relevance improvement of 35% over the prior Elasticsearch BM25 setup, validated through human relevance judgments.

Job 3: AI Engineer
Implemented a RAG-based customer support chatbot integrated with our existing ticketing system. Built the document ingestion pipeline (chunking, embedding via OpenAI embeddings, storing in Pinecone) and the answer-generation layer (initially GPT-4, then a fine-tuned smaller model for cost control). Designed the evaluation framework with both automatic metrics (BLEU, ROUGE) and human-in-the-loop quality scores. Deployment cut average ticket resolution time by 31% for the supported categories.
====================================================================================================
CAND_0030953
TITLE : Search Engineer

Job 1: Search Engineer
Trained and shipped multiple ranking models for our product's discovery feed using XGBoost and LightGBM. Designed features across three families: content metadata, user behavior signals, and item engagement history. Owned the offline-online correlation analysis that determined which offline metrics actually predicted A/B test outcomes. Worked closely with PMs to define the optimization target (click-through vs. dwell time vs. downstream conversion) — that work was as important as the modeling itself.

Job 2: NLP Engineer
Built a content recommendation system serving 10M+ users that combined collaborative filtering with content-based ranking. The system uses item-item similarity (via sentence-transformer embeddings) for cold starts and a gradient-boosted model trained on engagement signals for warm users. Most of my time went into the feature pipeline (~200 features) and the A/B testing infrastructure. The launch improved 7-day retention by 6% and time spent per session by 14%.

Job 3: Applied ML Engineer
Developed a semantic search feature for an internal knowledge base of ~500K documents. Used sentence-transformers (all-MiniLM-L6-v2 initially, later upgraded to bge-base) with FAISS for fast nearest-neighbor retrieval. Designed the query expansion module that handles vocabulary mismatch between user queries and document terms. Reported search-relevance improvement of 35% over the prior Elasticsearch BM25 setup, validated through human relevance judgments.

Job 4: Machine Learning Engineer
Trained and shipped multiple ranking models for our product's discovery feed using XGBoost and LightGBM. Designed features across three families: content metadata, user behavior signals, and item engagement history. Owned the offline-online correlation analysis that determined which offline metrics actually predicted A/B test outcomes. Worked closely with PMs to define the optimization target (click-through vs. dwell time vs. downstream conversion) — that work was as important as the modeling itself.

Job 5: Machine Learning Engineer
Implemented a RAG-based customer support chatbot integrated with our existing ticketing system. Built the document ingestion pipeline (chunking, embedding via OpenAI embeddings, storing in Pinecone) and the answer-generation layer (initially GPT-4, then a fine-tuned smaller model for cost control). Designed the evaluation framework with both automatic metrics (BLEU, ROUGE) and human-in-the-loop quality scores. Deployment cut average ticket resolution time by 31% for the supported categories.
====================================================================================================
CAND_0039754
TITLE : Senior Applied Scientist

Job 1: Senior Applied Scientist
Owned the end-to-end ranking pipeline at a recommendations-heavy consumer product: candidate sourcing → embedding generation (using a fine-tuned BGE-large) → Pinecone retrieval → learning-to-rank re-scoring (XGBoost) → behavioral-signal integration. The hardest part wasn't the ML — it was the evaluation: building offline metrics that actually predicted what the recommendation would do to live engagement. After three iterations we landed on a calibration approach using simulated A/B tests that has held up over the last 18 months.

Job 2: Senior ML Engineer — Search & Ranking
Owned the design and rollout of a large-scale semantic search system serving an internal corpus of 35M+ items. Migrated the existing BM25-only retrieval to a hybrid setup combining sparse and dense vectors (sentence-transformers, MPNet-base initially, later fine-tuned BGE-large for our domain). The new system reduced p95 retrieval latency by 60% while improving NDCG@10 by 18% on our held-out eval set. Spent substantial time on the boring-but-critical parts: incremental index refresh, embedding drift monitoring, online/offline metric correlation. Led a team of 4 engineers across the rollout.

Job 3: Senior Applied Scientist
Built a RAG-based ranking pipeline serving 50M+ queries per month for an internal recruiter-facing search product. The architecture combined BM25 + dense retrieval (BGE embeddings, FAISS HNSW) with an LLM-based re-ranker on the top-50, falling back to a learning-to-rank model when latency budget was tight. Designed the offline evaluation framework from scratch — NDCG, MRR, recall@K calibrated against online A/B engagement metrics. Drove the migration over 4 months including the recruiter-feedback loop that surfaced reranking edge cases.
====================================================================================================
CAND_0041611
TITLE : Staff Machine Learning Engineer

Job 1: Staff Machine Learning Engineer
Built a RAG-based ranking pipeline serving 50M+ queries per month for an internal recruiter-facing search product. The architecture combined BM25 + dense retrieval (BGE embeddings, FAISS HNSW) with an LLM-based re-ranker on the top-50, falling back to a learning-to-rank model when latency budget was tight. Designed the offline evaluation framework from scratch — NDCG, MRR, recall@K calibrated against online A/B engagement metrics. Drove the migration over 4 months including the recruiter-feedback loop that surfaced reranking edge cases.

Job 2: Senior Applied Scientist

In [ ]:
honeypot_scores = []

for r in records:

    penalty = 0

    years = r["profile"]["years_of_experience"]

    total_months = sum(
        job["duration_months"]
        for job in r["career_history"]
    )

    # Career duration impossible
    if total_months / 12 > years + 2:
        penalty += 2

    # Too many advanced skills
    advanced = sum(
        s["proficiency"] == "advanced"
        for s in r["skills"]
    )

    if advanced >= 10:
        penalty += 2

    # Too many skills
    if len(r["skills"]) > 25:
        penalty += 1

    honeypot_scores.append(
        (
            r["candidate_id"],
            penalty
        )
    )

In [ ]:
honeypot_df = pd.DataFrame(
    honeypot_scores,
    columns=[
        "candidate_id",
        "honeypot_penalty"
    ]
)

In [ ]:
top100 = top100.merge(
    honeypot_df,
    on="candidate_id",
    how="left"
)

top100["honeypot_penalty"] = (
    top100["honeypot_penalty"]
    .fillna(0)
)

In [ ]:
top100["final_score"] = (
    top100["final_score"]
    - 0.02 * top100["honeypot_penalty"]
)

In [ ]:
top100 = (
    top100
    .sort_values(
        "final_score",
        ascending=False
    )
    .reset_index(drop=True)
)

In [ ]:
top100.head()

,candidate_id,title,career,career_n,keyword,keyword_n,behavior,skill,skill_n,final_score,honeypot_penalty
0,CAND_0030953,Search Engineer,277,1.000000,45,0.849057,0.435344,3,0.375,0.835751,0
1,CAND_0039754,Senior Applied Scientist,212,0.765343,52,0.981132,0.843959,2,0.250,0.786407,0
2,CAND_0055992,AI Engineer,223,0.805054,45,0.849057,0.742778,4,0.500,0.781522,0
3,CAND_0018499,Senior Machine Learning Engineer,202,0.729242,43,0.811321,0.819666,7,0.875,0.777484,0
4,CAND_0077337,Staff Machine Learning Engineer,223,0.805054,35,0.660377,0.840351,7,0.875,0.772175,0

In [ ]:
record_map = {
    r["candidate_id"]: r
    for r in records
}

In [ ]:
jd_keywords = [
    "recommendation",
    "ranking",
    "semantic search",
    "retrieval",
    "dense retrieval",
    "faiss",
    "pinecone",
    "milvus",
    "embedding",
    "bm25",
    "bge",
    "llm",
    "rag",
    "lora",
    "qlora",
    "transformer",
    "xgboost",
    "lightgbm"
]

In [ ]:
matched_tech = {}

for cid in top100["candidate_id"]:

    r = record_map[cid]

    text = " ".join(
        job.get("description", "")
        for job in r["career_history"]
    ).lower()

    matched = []

    for kw in jd_keywords:
        if kw in text:
            matched.append(kw)

    matched_tech[cid] = matched[:5]

In [ ]:
for cid in top100["candidate_id"].head(5):
    print(cid)
    print(matched_tech[cid])
    print("-"*60)

CAND_0030953
['recommendation', 'ranking', 'semantic search', 'retrieval', 'faiss']
------------------------------------------------------------
CAND_0039754
['recommendation', 'ranking', 'semantic search', 'retrieval', 'dense retrieval']
------------------------------------------------------------
CAND_0055992
['recommendation', 'ranking', 'semantic search', 'retrieval', 'faiss']
------------------------------------------------------------
CAND_0018499
['ranking', 'retrieval', 'dense retrieval', 'faiss', 'embedding']
------------------------------------------------------------
CAND_0077337
['recommendation', 'ranking', 'semantic search', 'retrieval', 'embedding']
------------------------------------------------------------

In [ ]:
candidate_facts = {}

for cid in top100["candidate_id"]:

    r = record_map[cid]

    signal = r["redrob_signals"]

    candidate_facts[cid] = {
        "title": r["profile"]["current_title"],
        "experience": r["profile"]["years_of_experience"],
        "notice": signal["notice_period_days"],
        "response": signal["recruiter_response_rate"],
        "github": signal["github_activity_score"],
        "open": signal["open_to_work_flag"]
    }

In [ ]:
for cid in top100["candidate_id"].head(5):

    print("="*80)
    print(cid)
    print(candidate_facts[cid])

================================================================================
CAND_0030953
{'title': 'Search Engineer', 'experience': 7.8, 'notice': 45, 'response': 0.63, 'github': 21.0, 'open': False}
================================================================================
CAND_0039754
{'title': 'Senior Applied Scientist', 'experience': 16.2, 'notice': 30, 'response': 0.81, 'github': 77.5, 'open': True}
================================================================================
CAND_0055992
{'title': 'AI Engineer', 'experience': 16.9, 'notice': 60, 'response': 0.72, 'github': 65.3, 'open': True}
================================================================================
CAND_0018499
{'title': 'Senior Machine Learning Engineer', 'experience': 7.2, 'notice': 15, 'response': 0.61, 'github': 94.8, 'open': True}
================================================================================
CAND_0077337
{'title': 'Staff Machine Learning Engineer', 'experience': 7.0, 'notice': 60, 'response': 0.95, 'github': 68.0, 'open': True}

In [ ]:
reasonings = []

for cid in top100["candidate_id"]:

    facts = candidate_facts[cid]
    techs = matched_tech[cid]

    # ---------- Strength ----------
    strength = []

    strength.append(
        f"{facts['experience']:.1f} years of experience as a {facts['title']}."
    )

    if len(techs) > 0:
        strength.append(
            "Hands-on work in " + ", ".join(techs[:3]) + "."
        )

    # ---------- Positive Signals ----------
    positives = []

    if facts["response"] >= 0.80:
        positives.append("Strong recruiter engagement.")

    if facts["github"] >= 60:
        positives.append("High GitHub activity.")

    if facts["open"]:
        positives.append("Open to work.")

    # ---------- Concern ----------
    concern = ""

    if facts["notice"] >= 90:
        concern = "Long notice period may delay onboarding."

    elif facts["notice"] >= 60:
        concern = "Moderate notice period."

    elif not facts["open"]:
        concern = "Currently not marked open to work."

    # ---------- Final Reason ----------
    reason = " ".join(strength)

    if positives:
        reason += " " + " ".join(positives)

    if concern:
        reason += " " + concern

    reasonings.append(
        (
            cid,
            reason
        )
    )

In [ ]:
reason_df = pd.DataFrame(
    reasonings,
    columns=[
        "candidate_id",
        "reasoning"
    ]
)

In [ ]:
top100 = top100.merge(
    reason_df,
    on="candidate_id",
    how="left"
)

In [ ]:
top100[
    [
        "candidate_id",
        "reasoning"
    ]
].head(10)

   candidate_id                                          reasoning
0  CAND_0030953  7.8 years of experience as a Search Engineer. ...
1  CAND_0039754  16.2 years of experience as a Senior Applied S...
2  CAND_0055992  16.9 years of experience as a AI Engineer. Han...
3  CAND_0018499  7.2 years of experience as a Senior Machine Le...
4  CAND_0077337  7.0 years of experience as a Staff Machine Lea...
5  CAND_0046064  8.9 years of experience as a Senior NLP Engine...
6  CAND_0079387  6.9 years of experience as a AI Engineer. Hand...
7  CAND_0083307  7.8 years of experience as a Search Engineer. ...
8  CAND_0055905  8.1 years of experience as a Senior Machine Le...
9  CAND_0010770  15.2 years of experience as a Recommendation S...

In [ ]:
import re

def get_best_sentence(record):

    priority_words = {
        "improved":5,
        "built":4,
        "developed":4,
        "implemented":4,
        "designed":3,
        "trained":3,
        "deployed":3,
        "created":3,
        "owned":2,
        "recommendation":3,
        "ranking":3,
        "semantic search":3,
        "retrieval":3,
        "rag":3,
        "faiss":3,
        "pinecone":3,
        "bm25":3,
        "bge":3
    }

    best_sentence = ""
    best_score = -1

    for job in record["career_history"]:

        sentences = re.split(r'(?<=[.!?])\s+', job["description"])

        for sentence in sentences:

            s = sentence.lower()

            score = 0

            # important keywords
            for word, wt in priority_words.items():
                if word in s:
                    score += wt

            # numbers = impact
            if "%" in sentence:
                score += 5

            if re.search(r"\d+\s*M", sentence):
                score += 5

            if re.search(r"\d+\s*K", sentence):
                score += 4

            if len(sentence) > 250:
                score -= 2

            if score > best_score:
                best_score = score
                best_sentence = sentence.strip()

    return best_sentence

In [ ]:
def detect_project(text):

    text = text.lower()

    if "recommendation" in text:
        return "recommendation"

    elif "semantic search" in text:
        return "semantic_search"

    elif "rag" in text:
        return "rag"

    elif "ranking" in text:
        return "ranking"

    elif "retrieval" in text:
        return "retrieval"

    return "general"

In [ ]:
def extract_tech(text):

    techs = []

    keywords = [
        "FAISS",
        "Pinecone",
        "Milvus",
        "BM25",
        "BGE",
        "Sentence Transformer",
        "OpenAI",
        "GPT-4",
        "LoRA",
        "QLoRA",
        "LightGBM",
        "XGBoost"
    ]

    lower = text.lower()

    for tech in keywords:

        if tech.lower() in lower:
            techs.append(tech)

    return techs

In [ ]:
import re

def extract_metric(text):

    m = re.findall(r'\d+(?:\.\d+)?(?:M\+?|K\+?|%)', text)

    return ", ".join(m)

In [ ]:
def summarize_project(sentence):

    s = sentence.lower()

    if "pinecone" in s and "openai" in s:
        return "Built a production RAG pipeline using OpenAI embeddings and Pinecone for enterprise knowledge retrieval."

    elif "recommendation" in s:
        return "Built large-scale recommendation systems with production ranking pipelines."

    elif "semantic search" in s:
        return "Developed semantic search solutions using dense embeddings and vector search."

    elif "ranking" in s:
        return "Designed production ranking pipelines for search and recommendation systems."

    elif "retrieval" in s:
        return "Implemented dense retrieval pipelines for large-scale search systems."

    return sentence

In [ ]:
import re

def extract_metrics(text):

    pattern = r'\d+(?:\.\d+)?(?:M\+?|K\+?|%)'

    return re.findall(pattern, text)

In [ ]:
def extract_technologies(text):

    techs = [
        "FAISS",
        "Pinecone",
        "Milvus",
        "BM25",
        "Semantic Search",
        "Recommendation",
        "Ranking",
        "RAG",
        "Embeddings",
        "BGE",
        "Sentence Transformers",
        "XGBoost",
        "LightGBM",
        "LoRA",
        "QLoRA"
    ]

    found = []

    lower = text.lower()

    for tech in techs:

        if tech.lower() in lower:
            found.append(tech)

    return found

In [130]:
fit_templates = [
    "Closely matches the technical requirements of the target role.",
    "Demonstrates strong production experience relevant to the job description.",
    "Career history aligns well with the search, retrieval and recommendation requirements.",
    "Previous projects closely match the responsibilities of this position.",
    "Technical background is highly relevant for production AI systems.",
    "Shows practical experience building large-scale ML and retrieval solutions."
]

reasonings = []

for cid in top100["candidate_id"]:

    r = record_map[cid]
    signal = r["redrob_signals"]

    intro = (
        f"{r['profile']['current_title']} with "
        f"{r['profile']['years_of_experience']:.1f} years of experience."
    )

    achievement = get_best_sentence(r)

    candidate_number = int(cid.split("_")[1])

    fit = fit_templates[
        candidate_number % len(fit_templates)
    ]




    positives = []

    if signal["github_activity_score"] >= 60:
      positives.append("High GitHub activity indicates continued technical engagement.")

    if signal["recruiter_response_rate"] >= 0.80:
      positives.append("High recruiter response suggests strong market interest.")
    if signal["open_to_work_flag"]:
      positives.append("Currently open to new opportunities.")

    concern = ""

    if signal["notice_period_days"] >= 90:
        concern = "Long notice period may delay onboarding."

    elif signal["notice_period_days"] >= 60:
        concern = "60-day notice period."

    elif not signal["open_to_work_flag"]:
        concern = "Currently not marked open to work."

    reasoning = (
        intro
        + " "
        + achievement
        + " "
        + fit
    )

    if positives:
        reasoning += " " + " ".join(positives)

    if concern:
        reasoning += " " + concern

    reasonings.append((cid, reasoning))

In [131]:
reason_df = pd.DataFrame(
    reasonings,
    columns=["candidate_id", "reasoning"]
)

In [132]:
top100 = top100.drop(
    columns=["reasoning", "reasoning_x", "reasoning_y"],
    errors="ignore"
)

top100 = top100.merge(
    reason_df,
    on="candidate_id",
    how="left"
)

In [144]:
top100.shape

(100000, 12)

In [133]:
top100.columns

Index(['candidate_id', 'title', 'career', 'career_n', 'keyword', 'keyword_n',
       'behavior', 'skill', 'skill_n', 'final_score', 'honeypot_penalty',
       'reasoning'],
      dtype='object')

In [134]:
top100[["candidate_id", "reasoning"]].head(10)

   candidate_id                                          reasoning
0  CAND_0030953  Search Engineer with 7.8 years of experience. ...
1  CAND_0039754  Senior Applied Scientist with 16.2 years of ex...
2  CAND_0055992  AI Engineer with 16.9 years of experience. Bui...
3  CAND_0018499  Senior Machine Learning Engineer with 7.2 year...
4  CAND_0077337  Staff Machine Learning Engineer with 7.0 years...
5  CAND_0046064  Senior NLP Engineer with 8.9 years of experien...
6  CAND_0079387  AI Engineer with 6.9 years of experience. Buil...
7  CAND_0083307  Search Engineer with 7.8 years of experience. ...
8  CAND_0055905  Senior Machine Learning Engineer with 8.1 year...
9  CAND_0010770  Recommendation Systems Engineer with 15.2 year...

In [158]:
submission = top100.copy()

submission = submission.sort_values(
    "final_score",
    ascending=False
).reset_index(drop=True)

submission["rank"] = submission.index + 1

submission = submission[
    [
        "candidate_id",
        "rank",
        "final_score",
        "reasoning"
    ]
]

submission.columns = [
    "candidate_id",
    "rank",
    "score",
    "reasoning"
]

submission.head()

,candidate_id,rank,score,reasoning
0,CAND_0030953,1,0.835751,Search Engineer with 7.8 years of experience. ...
1,CAND_0039754,2,0.786407,Senior Applied Scientist with 16.2 years of ex...
2,CAND_0055992,3,0.781522,AI Engineer with 16.9 years of experience. Bui...
3,CAND_0018499,4,0.777484,Senior Machine Learning Engineer with 7.2 year...
4,CAND_0077337,5,0.772175,Staff Machine Learning Engineer with 7.0 years...

In [136]:

submission.to_excel(
    "submission.xlsx",
    index=False
)

In [140]:
submission["score"] = submission["score"].round(4)

In [157]:
submission.columns

Index(['candidate_id', 'title', 'career', 'career_n', 'keyword', 'keyword_n',
       'behavior', 'skill', 'skill_n', 'final_score', 'rank', 'score'],
      dtype='object')

In [142]:

submission.to_excel(
    "submission.xlsx",
    index=False
)

In [161]:
submission.shape

(100, 12)

In [163]:
submission.to_excel(
    "submission.xlsx",
    index=False
)